// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package vpnipsecfilter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ipsecAddressKey struct {
	_       structs.HostLayout
	Family  uint32
	Address [16]uint8
}

type ipsecDestinationKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Family    uint32
	Address   [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ipsecMapDenied           = "denied"
	ipsecMapDestinations     = "destinations"
	ipsecProgVpnIpsecIngress = "vpn_ipsec_ingress"
)

// loadIpsec returns the embedded CollectionSpec for ipsec.
func loadIpsec() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IpsecBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ipsec: %w", err)
	}

	return spec, err
}

// loadIpsecObjects loads ipsec and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ipsecObjects
//	*ipsecPrograms
//	*ipsecMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIpsecObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadIpsec()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ipsecSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipsecSpecs struct {
	ipsecProgramSpecs
	ipsecMapSpecs
	ipsecVariableSpecs
}

// ipsecProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipsecProgramSpecs struct {
	VpnIpsecIngress *ebpf.ProgramSpec `ebpf:"vpn_ipsec_ingress"`
}

// ipsecMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipsecMapSpecs struct {
	Denied       *ebpf.MapSpec `ebpf:"denied"`
	Destinations *ebpf.MapSpec `ebpf:"destinations"`
}

// ipsecVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ipsecVariableSpecs struct {
}

// ipsecObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIpsecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipsecObjects struct {
	ipsecPrograms
	ipsecMaps
	ipsecVariables
}

func (o *ipsecObjects) Close() error {
	return _IpsecClose(
		&o.ipsecPrograms,
		&o.ipsecMaps,
	)
}

// ipsecMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIpsecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipsecMaps struct {
	Denied       *ebpf.Map `ebpf:"denied"`
	Destinations *ebpf.Map `ebpf:"destinations"`
}

func (m *ipsecMaps) Close() error {
	return _IpsecClose(
		m.Denied,
		m.Destinations,
	)
}

// ipsecVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIpsecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipsecVariables struct {
}

// ipsecPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIpsecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ipsecPrograms struct {
	VpnIpsecIngress *ebpf.Program `ebpf:"vpn_ipsec_ingress"`
}

func (p *ipsecPrograms) Close() error {
	return _IpsecClose(
		p.VpnIpsecIngress,
	)
}

func _IpsecClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ipsec_bpfel.o
var _IpsecBytes []byte
