//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 The Cozyplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	sdn "github.com/lllamnyp/cozyplane/api/sdn"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*LocalVPCRef)(nil), (*sdn.LocalVPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(a.(*LocalVPCRef), b.(*sdn.LocalVPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.LocalVPCRef)(nil), (*LocalVPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(a.(*sdn.LocalVPCRef), b.(*LocalVPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Port)(nil), (*sdn.Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Port_To_sdn_Port(a.(*Port), b.(*sdn.Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.Port)(nil), (*Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_Port_To_v1alpha1_Port(a.(*sdn.Port), b.(*Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortList)(nil), (*sdn.PortList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PortList_To_sdn_PortList(a.(*PortList), b.(*sdn.PortList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.PortList)(nil), (*PortList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_PortList_To_v1alpha1_PortList(a.(*sdn.PortList), b.(*PortList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortSpec)(nil), (*sdn.PortSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PortSpec_To_sdn_PortSpec(a.(*PortSpec), b.(*sdn.PortSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.PortSpec)(nil), (*PortSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_PortSpec_To_v1alpha1_PortSpec(a.(*sdn.PortSpec), b.(*PortSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPC)(nil), (*sdn.VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPC_To_sdn_VPC(a.(*VPC), b.(*sdn.VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPC)(nil), (*VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPC_To_v1alpha1_VPC(a.(*sdn.VPC), b.(*VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCBinding)(nil), (*sdn.VPCBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCBinding_To_sdn_VPCBinding(a.(*VPCBinding), b.(*sdn.VPCBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCBinding)(nil), (*VPCBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCBinding_To_v1alpha1_VPCBinding(a.(*sdn.VPCBinding), b.(*VPCBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCBindingList)(nil), (*sdn.VPCBindingList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(a.(*VPCBindingList), b.(*sdn.VPCBindingList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCBindingList)(nil), (*VPCBindingList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(a.(*sdn.VPCBindingList), b.(*VPCBindingList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCBindingSpec)(nil), (*sdn.VPCBindingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(a.(*VPCBindingSpec), b.(*sdn.VPCBindingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCBindingSpec)(nil), (*VPCBindingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(a.(*sdn.VPCBindingSpec), b.(*VPCBindingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCList)(nil), (*sdn.VPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCList_To_sdn_VPCList(a.(*VPCList), b.(*sdn.VPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCList)(nil), (*VPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCList_To_v1alpha1_VPCList(a.(*sdn.VPCList), b.(*VPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeering)(nil), (*sdn.VPCPeering)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeering_To_sdn_VPCPeering(a.(*VPCPeering), b.(*sdn.VPCPeering), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeering)(nil), (*VPCPeering)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeering_To_v1alpha1_VPCPeering(a.(*sdn.VPCPeering), b.(*VPCPeering), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeeringList)(nil), (*sdn.VPCPeeringList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(a.(*VPCPeeringList), b.(*sdn.VPCPeeringList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeeringList)(nil), (*VPCPeeringList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(a.(*sdn.VPCPeeringList), b.(*VPCPeeringList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeeringSpec)(nil), (*sdn.VPCPeeringSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(a.(*VPCPeeringSpec), b.(*sdn.VPCPeeringSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeeringSpec)(nil), (*VPCPeeringSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(a.(*sdn.VPCPeeringSpec), b.(*VPCPeeringSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeeringStatus)(nil), (*sdn.VPCPeeringStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(a.(*VPCPeeringStatus), b.(*sdn.VPCPeeringStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeeringStatus)(nil), (*VPCPeeringStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(a.(*sdn.VPCPeeringStatus), b.(*VPCPeeringStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCRef)(nil), (*sdn.VPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCRef_To_sdn_VPCRef(a.(*VPCRef), b.(*sdn.VPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCRef)(nil), (*VPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCRef_To_v1alpha1_VPCRef(a.(*sdn.VPCRef), b.(*VPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCSpec)(nil), (*sdn.VPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(a.(*VPCSpec), b.(*sdn.VPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCSpec)(nil), (*VPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(a.(*sdn.VPCSpec), b.(*VPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCStatus)(nil), (*sdn.VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(a.(*VPCStatus), b.(*sdn.VPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCStatus)(nil), (*VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(a.(*sdn.VPCStatus), b.(*VPCStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(in *LocalVPCRef, out *sdn.LocalVPCRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef is an autogenerated conversion function.
func Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(in *LocalVPCRef, out *sdn.LocalVPCRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(in, out, s)
}

func autoConvert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(in *sdn.LocalVPCRef, out *LocalVPCRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef is an autogenerated conversion function.
func Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(in *sdn.LocalVPCRef, out *LocalVPCRef, s conversion.Scope) error {
	return autoConvert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(in, out, s)
}

func autoConvert_v1alpha1_Port_To_sdn_Port(in *Port, out *sdn.Port, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PortSpec_To_sdn_PortSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Port_To_sdn_Port is an autogenerated conversion function.
func Convert_v1alpha1_Port_To_sdn_Port(in *Port, out *sdn.Port, s conversion.Scope) error {
	return autoConvert_v1alpha1_Port_To_sdn_Port(in, out, s)
}

func autoConvert_sdn_Port_To_v1alpha1_Port(in *sdn.Port, out *Port, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_PortSpec_To_v1alpha1_PortSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_Port_To_v1alpha1_Port is an autogenerated conversion function.
func Convert_sdn_Port_To_v1alpha1_Port(in *sdn.Port, out *Port, s conversion.Scope) error {
	return autoConvert_sdn_Port_To_v1alpha1_Port(in, out, s)
}

func autoConvert_v1alpha1_PortList_To_sdn_PortList(in *PortList, out *sdn.PortList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.Port)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PortList_To_sdn_PortList is an autogenerated conversion function.
func Convert_v1alpha1_PortList_To_sdn_PortList(in *PortList, out *sdn.PortList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PortList_To_sdn_PortList(in, out, s)
}

func autoConvert_sdn_PortList_To_v1alpha1_PortList(in *sdn.PortList, out *PortList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Port)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_PortList_To_v1alpha1_PortList is an autogenerated conversion function.
func Convert_sdn_PortList_To_v1alpha1_PortList(in *sdn.PortList, out *PortList, s conversion.Scope) error {
	return autoConvert_sdn_PortList_To_v1alpha1_PortList(in, out, s)
}

func autoConvert_v1alpha1_PortSpec_To_sdn_PortSpec(in *PortSpec, out *sdn.PortSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPCRef_To_sdn_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.IP = in.IP
	out.FabricIP = in.FabricIP
	out.MAC = in.MAC
	out.Node = in.Node
	out.NodeIP = in.NodeIP
	out.PodNamespace = in.PodNamespace
	out.PodName = in.PodName
	return nil
}

// Convert_v1alpha1_PortSpec_To_sdn_PortSpec is an autogenerated conversion function.
func Convert_v1alpha1_PortSpec_To_sdn_PortSpec(in *PortSpec, out *sdn.PortSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PortSpec_To_sdn_PortSpec(in, out, s)
}

func autoConvert_sdn_PortSpec_To_v1alpha1_PortSpec(in *sdn.PortSpec, out *PortSpec, s conversion.Scope) error {
	if err := Convert_sdn_VPCRef_To_v1alpha1_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.IP = in.IP
	out.FabricIP = in.FabricIP
	out.MAC = in.MAC
	out.Node = in.Node
	out.NodeIP = in.NodeIP
	out.PodNamespace = in.PodNamespace
	out.PodName = in.PodName
	return nil
}

// Convert_sdn_PortSpec_To_v1alpha1_PortSpec is an autogenerated conversion function.
func Convert_sdn_PortSpec_To_v1alpha1_PortSpec(in *sdn.PortSpec, out *PortSpec, s conversion.Scope) error {
	return autoConvert_sdn_PortSpec_To_v1alpha1_PortSpec(in, out, s)
}

func autoConvert_v1alpha1_VPC_To_sdn_VPC(in *VPC, out *sdn.VPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPC_To_sdn_VPC is an autogenerated conversion function.
func Convert_v1alpha1_VPC_To_sdn_VPC(in *VPC, out *sdn.VPC, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPC_To_sdn_VPC(in, out, s)
}

func autoConvert_sdn_VPC_To_v1alpha1_VPC(in *sdn.VPC, out *VPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPC_To_v1alpha1_VPC is an autogenerated conversion function.
func Convert_sdn_VPC_To_v1alpha1_VPC(in *sdn.VPC, out *VPC, s conversion.Scope) error {
	return autoConvert_sdn_VPC_To_v1alpha1_VPC(in, out, s)
}

func autoConvert_v1alpha1_VPCBinding_To_sdn_VPCBinding(in *VPCBinding, out *sdn.VPCBinding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCBinding_To_sdn_VPCBinding is an autogenerated conversion function.
func Convert_v1alpha1_VPCBinding_To_sdn_VPCBinding(in *VPCBinding, out *sdn.VPCBinding, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCBinding_To_sdn_VPCBinding(in, out, s)
}

func autoConvert_sdn_VPCBinding_To_v1alpha1_VPCBinding(in *sdn.VPCBinding, out *VPCBinding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCBinding_To_v1alpha1_VPCBinding is an autogenerated conversion function.
func Convert_sdn_VPCBinding_To_v1alpha1_VPCBinding(in *sdn.VPCBinding, out *VPCBinding, s conversion.Scope) error {
	return autoConvert_sdn_VPCBinding_To_v1alpha1_VPCBinding(in, out, s)
}

func autoConvert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(in *VPCBindingList, out *sdn.VPCBindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPCBinding)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList is an autogenerated conversion function.
func Convert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(in *VPCBindingList, out *sdn.VPCBindingList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(in, out, s)
}

func autoConvert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(in *sdn.VPCBindingList, out *VPCBindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPCBinding)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList is an autogenerated conversion function.
func Convert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(in *sdn.VPCBindingList, out *VPCBindingList, s conversion.Scope) error {
	return autoConvert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(in, out, s)
}

func autoConvert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(in *VPCBindingSpec, out *sdn.VPCBindingSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPCRef_To_sdn_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(in *VPCBindingSpec, out *sdn.VPCBindingSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(in, out, s)
}

func autoConvert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(in *sdn.VPCBindingSpec, out *VPCBindingSpec, s conversion.Scope) error {
	if err := Convert_sdn_VPCRef_To_v1alpha1_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec is an autogenerated conversion function.
func Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(in *sdn.VPCBindingSpec, out *VPCBindingSpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(in, out, s)
}

func autoConvert_v1alpha1_VPCList_To_sdn_VPCList(in *VPCList, out *sdn.VPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCList_To_sdn_VPCList is an autogenerated conversion function.
func Convert_v1alpha1_VPCList_To_sdn_VPCList(in *VPCList, out *sdn.VPCList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCList_To_sdn_VPCList(in, out, s)
}

func autoConvert_sdn_VPCList_To_v1alpha1_VPCList(in *sdn.VPCList, out *VPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCList_To_v1alpha1_VPCList is an autogenerated conversion function.
func Convert_sdn_VPCList_To_v1alpha1_VPCList(in *sdn.VPCList, out *VPCList, s conversion.Scope) error {
	return autoConvert_sdn_VPCList_To_v1alpha1_VPCList(in, out, s)
}

func autoConvert_v1alpha1_VPCPeering_To_sdn_VPCPeering(in *VPCPeering, out *sdn.VPCPeering, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCPeering_To_sdn_VPCPeering is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeering_To_sdn_VPCPeering(in *VPCPeering, out *sdn.VPCPeering, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeering_To_sdn_VPCPeering(in, out, s)
}

func autoConvert_sdn_VPCPeering_To_v1alpha1_VPCPeering(in *sdn.VPCPeering, out *VPCPeering, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCPeering_To_v1alpha1_VPCPeering is an autogenerated conversion function.
func Convert_sdn_VPCPeering_To_v1alpha1_VPCPeering(in *sdn.VPCPeering, out *VPCPeering, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeering_To_v1alpha1_VPCPeering(in, out, s)
}

func autoConvert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(in *VPCPeeringList, out *sdn.VPCPeeringList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPCPeering)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(in *VPCPeeringList, out *sdn.VPCPeeringList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(in, out, s)
}

func autoConvert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(in *sdn.VPCPeeringList, out *VPCPeeringList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPCPeering)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList is an autogenerated conversion function.
func Convert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(in *sdn.VPCPeeringList, out *VPCPeeringList, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(in, out, s)
}

func autoConvert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(in *VPCPeeringSpec, out *sdn.VPCPeeringSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCRef_To_sdn_VPCRef(&in.PeerRef, &out.PeerRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(in *VPCPeeringSpec, out *sdn.VPCPeeringSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(in, out, s)
}

func autoConvert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(in *sdn.VPCPeeringSpec, out *VPCPeeringSpec, s conversion.Scope) error {
	if err := Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCRef_To_v1alpha1_VPCRef(&in.PeerRef, &out.PeerRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec is an autogenerated conversion function.
func Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(in *sdn.VPCPeeringSpec, out *VPCPeeringSpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(in, out, s)
}

func autoConvert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(in *VPCPeeringStatus, out *sdn.VPCPeeringStatus, s conversion.Scope) error {
	out.Phase = sdn.VPCPeeringPhase(in.Phase)
	out.PeerVNI = in.PeerVNI
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(in *VPCPeeringStatus, out *sdn.VPCPeeringStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(in, out, s)
}

func autoConvert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(in *sdn.VPCPeeringStatus, out *VPCPeeringStatus, s conversion.Scope) error {
	out.Phase = VPCPeeringPhase(in.Phase)
	out.PeerVNI = in.PeerVNI
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus is an autogenerated conversion function.
func Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(in *sdn.VPCPeeringStatus, out *VPCPeeringStatus, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(in, out, s)
}

func autoConvert_v1alpha1_VPCRef_To_sdn_VPCRef(in *VPCRef, out *sdn.VPCRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_VPCRef_To_sdn_VPCRef is an autogenerated conversion function.
func Convert_v1alpha1_VPCRef_To_sdn_VPCRef(in *VPCRef, out *sdn.VPCRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCRef_To_sdn_VPCRef(in, out, s)
}

func autoConvert_sdn_VPCRef_To_v1alpha1_VPCRef(in *sdn.VPCRef, out *VPCRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_sdn_VPCRef_To_v1alpha1_VPCRef is an autogenerated conversion function.
func Convert_sdn_VPCRef_To_v1alpha1_VPCRef(in *sdn.VPCRef, out *VPCRef, s conversion.Scope) error {
	return autoConvert_sdn_VPCRef_To_v1alpha1_VPCRef(in, out, s)
}

func autoConvert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in *VPCSpec, out *sdn.VPCSpec, s conversion.Scope) error {
	out.CIDRs = *(*[]string)(unsafe.Pointer(&in.CIDRs))
	out.MTU = in.MTU
	return nil
}

// Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in *VPCSpec, out *sdn.VPCSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in, out, s)
}

func autoConvert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in *sdn.VPCSpec, out *VPCSpec, s conversion.Scope) error {
	out.CIDRs = *(*[]string)(unsafe.Pointer(&in.CIDRs))
	out.MTU = in.MTU
	return nil
}

// Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec is an autogenerated conversion function.
func Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in *sdn.VPCSpec, out *VPCSpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in, out, s)
}

func autoConvert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in *VPCStatus, out *sdn.VPCStatus, s conversion.Scope) error {
	out.VNI = in.VNI
	out.Phase = sdn.VPCPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in *VPCStatus, out *sdn.VPCStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in, out, s)
}

func autoConvert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in *sdn.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	out.VNI = in.VNI
	out.Phase = VPCPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus is an autogenerated conversion function.
func Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in *sdn.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	return autoConvert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in, out, s)
}
