//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 The Cozyplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	sdn "github.com/lllamnyp/cozyplane/api/sdn"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*FloatingIP)(nil), (*sdn.FloatingIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FloatingIP_To_sdn_FloatingIP(a.(*FloatingIP), b.(*sdn.FloatingIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.FloatingIP)(nil), (*FloatingIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_FloatingIP_To_v1alpha1_FloatingIP(a.(*sdn.FloatingIP), b.(*FloatingIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FloatingIPList)(nil), (*sdn.FloatingIPList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FloatingIPList_To_sdn_FloatingIPList(a.(*FloatingIPList), b.(*sdn.FloatingIPList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.FloatingIPList)(nil), (*FloatingIPList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_FloatingIPList_To_v1alpha1_FloatingIPList(a.(*sdn.FloatingIPList), b.(*FloatingIPList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FloatingIPSpec)(nil), (*sdn.FloatingIPSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FloatingIPSpec_To_sdn_FloatingIPSpec(a.(*FloatingIPSpec), b.(*sdn.FloatingIPSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.FloatingIPSpec)(nil), (*FloatingIPSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_FloatingIPSpec_To_v1alpha1_FloatingIPSpec(a.(*sdn.FloatingIPSpec), b.(*FloatingIPSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FloatingIPStatus)(nil), (*sdn.FloatingIPStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FloatingIPStatus_To_sdn_FloatingIPStatus(a.(*FloatingIPStatus), b.(*sdn.FloatingIPStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.FloatingIPStatus)(nil), (*FloatingIPStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_FloatingIPStatus_To_v1alpha1_FloatingIPStatus(a.(*sdn.FloatingIPStatus), b.(*FloatingIPStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewall)(nil), (*sdn.HostFirewall)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewall_To_sdn_HostFirewall(a.(*HostFirewall), b.(*sdn.HostFirewall), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewall)(nil), (*HostFirewall)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewall_To_v1alpha1_HostFirewall(a.(*sdn.HostFirewall), b.(*HostFirewall), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewallEgressRule)(nil), (*sdn.HostFirewallEgressRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewallEgressRule_To_sdn_HostFirewallEgressRule(a.(*HostFirewallEgressRule), b.(*sdn.HostFirewallEgressRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewallEgressRule)(nil), (*HostFirewallEgressRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewallEgressRule_To_v1alpha1_HostFirewallEgressRule(a.(*sdn.HostFirewallEgressRule), b.(*HostFirewallEgressRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewallList)(nil), (*sdn.HostFirewallList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewallList_To_sdn_HostFirewallList(a.(*HostFirewallList), b.(*sdn.HostFirewallList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewallList)(nil), (*HostFirewallList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewallList_To_v1alpha1_HostFirewallList(a.(*sdn.HostFirewallList), b.(*HostFirewallList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewallPeer)(nil), (*sdn.HostFirewallPeer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewallPeer_To_sdn_HostFirewallPeer(a.(*HostFirewallPeer), b.(*sdn.HostFirewallPeer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewallPeer)(nil), (*HostFirewallPeer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewallPeer_To_v1alpha1_HostFirewallPeer(a.(*sdn.HostFirewallPeer), b.(*HostFirewallPeer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewallPort)(nil), (*sdn.HostFirewallPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewallPort_To_sdn_HostFirewallPort(a.(*HostFirewallPort), b.(*sdn.HostFirewallPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewallPort)(nil), (*HostFirewallPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewallPort_To_v1alpha1_HostFirewallPort(a.(*sdn.HostFirewallPort), b.(*HostFirewallPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewallRule)(nil), (*sdn.HostFirewallRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewallRule_To_sdn_HostFirewallRule(a.(*HostFirewallRule), b.(*sdn.HostFirewallRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewallRule)(nil), (*HostFirewallRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewallRule_To_v1alpha1_HostFirewallRule(a.(*sdn.HostFirewallRule), b.(*HostFirewallRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewallSpec)(nil), (*sdn.HostFirewallSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewallSpec_To_sdn_HostFirewallSpec(a.(*HostFirewallSpec), b.(*sdn.HostFirewallSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewallSpec)(nil), (*HostFirewallSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewallSpec_To_v1alpha1_HostFirewallSpec(a.(*sdn.HostFirewallSpec), b.(*HostFirewallSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostFirewallStatus)(nil), (*sdn.HostFirewallStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostFirewallStatus_To_sdn_HostFirewallStatus(a.(*HostFirewallStatus), b.(*sdn.HostFirewallStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.HostFirewallStatus)(nil), (*HostFirewallStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_HostFirewallStatus_To_v1alpha1_HostFirewallStatus(a.(*sdn.HostFirewallStatus), b.(*HostFirewallStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LocalVPCRef)(nil), (*sdn.LocalVPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(a.(*LocalVPCRef), b.(*sdn.LocalVPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.LocalVPCRef)(nil), (*LocalVPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(a.(*sdn.LocalVPCRef), b.(*LocalVPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Port)(nil), (*sdn.Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Port_To_sdn_Port(a.(*Port), b.(*sdn.Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.Port)(nil), (*Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_Port_To_v1alpha1_Port(a.(*sdn.Port), b.(*Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortList)(nil), (*sdn.PortList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PortList_To_sdn_PortList(a.(*PortList), b.(*sdn.PortList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.PortList)(nil), (*PortList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_PortList_To_v1alpha1_PortList(a.(*sdn.PortList), b.(*PortList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortSpec)(nil), (*sdn.PortSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PortSpec_To_sdn_PortSpec(a.(*PortSpec), b.(*sdn.PortSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.PortSpec)(nil), (*PortSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_PortSpec_To_v1alpha1_PortSpec(a.(*sdn.PortSpec), b.(*PortSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PortStatus)(nil), (*sdn.PortStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PortStatus_To_sdn_PortStatus(a.(*PortStatus), b.(*sdn.PortStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.PortStatus)(nil), (*PortStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_PortStatus_To_v1alpha1_PortStatus(a.(*sdn.PortStatus), b.(*PortStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroup)(nil), (*sdn.SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroup_To_sdn_SecurityGroup(a.(*SecurityGroup), b.(*sdn.SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroup)(nil), (*SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroup_To_v1alpha1_SecurityGroup(a.(*sdn.SecurityGroup), b.(*SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupEgressRule)(nil), (*sdn.SecurityGroupEgressRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroupEgressRule_To_sdn_SecurityGroupEgressRule(a.(*SecurityGroupEgressRule), b.(*sdn.SecurityGroupEgressRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroupEgressRule)(nil), (*SecurityGroupEgressRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroupEgressRule_To_v1alpha1_SecurityGroupEgressRule(a.(*sdn.SecurityGroupEgressRule), b.(*SecurityGroupEgressRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupList)(nil), (*sdn.SecurityGroupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroupList_To_sdn_SecurityGroupList(a.(*SecurityGroupList), b.(*sdn.SecurityGroupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroupList)(nil), (*SecurityGroupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroupList_To_v1alpha1_SecurityGroupList(a.(*sdn.SecurityGroupList), b.(*SecurityGroupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupPeer)(nil), (*sdn.SecurityGroupPeer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroupPeer_To_sdn_SecurityGroupPeer(a.(*SecurityGroupPeer), b.(*sdn.SecurityGroupPeer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroupPeer)(nil), (*SecurityGroupPeer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroupPeer_To_v1alpha1_SecurityGroupPeer(a.(*sdn.SecurityGroupPeer), b.(*SecurityGroupPeer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupPort)(nil), (*sdn.SecurityGroupPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroupPort_To_sdn_SecurityGroupPort(a.(*SecurityGroupPort), b.(*sdn.SecurityGroupPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroupPort)(nil), (*SecurityGroupPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroupPort_To_v1alpha1_SecurityGroupPort(a.(*sdn.SecurityGroupPort), b.(*SecurityGroupPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupRule)(nil), (*sdn.SecurityGroupRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroupRule_To_sdn_SecurityGroupRule(a.(*SecurityGroupRule), b.(*sdn.SecurityGroupRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroupRule)(nil), (*SecurityGroupRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroupRule_To_v1alpha1_SecurityGroupRule(a.(*sdn.SecurityGroupRule), b.(*SecurityGroupRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupSpec)(nil), (*sdn.SecurityGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroupSpec_To_sdn_SecurityGroupSpec(a.(*SecurityGroupSpec), b.(*sdn.SecurityGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroupSpec)(nil), (*SecurityGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroupSpec_To_v1alpha1_SecurityGroupSpec(a.(*sdn.SecurityGroupSpec), b.(*SecurityGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroupStatus)(nil), (*sdn.SecurityGroupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroupStatus_To_sdn_SecurityGroupStatus(a.(*SecurityGroupStatus), b.(*sdn.SecurityGroupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.SecurityGroupStatus)(nil), (*SecurityGroupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_SecurityGroupStatus_To_v1alpha1_SecurityGroupStatus(a.(*sdn.SecurityGroupStatus), b.(*SecurityGroupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceRef)(nil), (*sdn.ServiceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceRef_To_sdn_ServiceRef(a.(*ServiceRef), b.(*sdn.ServiceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.ServiceRef)(nil), (*ServiceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_ServiceRef_To_v1alpha1_ServiceRef(a.(*sdn.ServiceRef), b.(*ServiceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceVIP)(nil), (*sdn.ServiceVIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceVIP_To_sdn_ServiceVIP(a.(*ServiceVIP), b.(*sdn.ServiceVIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.ServiceVIP)(nil), (*ServiceVIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_ServiceVIP_To_v1alpha1_ServiceVIP(a.(*sdn.ServiceVIP), b.(*ServiceVIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceVIPList)(nil), (*sdn.ServiceVIPList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceVIPList_To_sdn_ServiceVIPList(a.(*ServiceVIPList), b.(*sdn.ServiceVIPList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.ServiceVIPList)(nil), (*ServiceVIPList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_ServiceVIPList_To_v1alpha1_ServiceVIPList(a.(*sdn.ServiceVIPList), b.(*ServiceVIPList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceVIPSpec)(nil), (*sdn.ServiceVIPSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceVIPSpec_To_sdn_ServiceVIPSpec(a.(*ServiceVIPSpec), b.(*sdn.ServiceVIPSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.ServiceVIPSpec)(nil), (*ServiceVIPSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_ServiceVIPSpec_To_v1alpha1_ServiceVIPSpec(a.(*sdn.ServiceVIPSpec), b.(*ServiceVIPSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceVIPStatus)(nil), (*sdn.ServiceVIPStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceVIPStatus_To_sdn_ServiceVIPStatus(a.(*ServiceVIPStatus), b.(*sdn.ServiceVIPStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.ServiceVIPStatus)(nil), (*ServiceVIPStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_ServiceVIPStatus_To_v1alpha1_ServiceVIPStatus(a.(*sdn.ServiceVIPStatus), b.(*ServiceVIPStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VIPBackend)(nil), (*sdn.VIPBackend)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VIPBackend_To_sdn_VIPBackend(a.(*VIPBackend), b.(*sdn.VIPBackend), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VIPBackend)(nil), (*VIPBackend)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VIPBackend_To_v1alpha1_VIPBackend(a.(*sdn.VIPBackend), b.(*VIPBackend), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VIPBackendPort)(nil), (*sdn.VIPBackendPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VIPBackendPort_To_sdn_VIPBackendPort(a.(*VIPBackendPort), b.(*sdn.VIPBackendPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VIPBackendPort)(nil), (*VIPBackendPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VIPBackendPort_To_v1alpha1_VIPBackendPort(a.(*sdn.VIPBackendPort), b.(*VIPBackendPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VIPPort)(nil), (*sdn.VIPPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VIPPort_To_sdn_VIPPort(a.(*VIPPort), b.(*sdn.VIPPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VIPPort)(nil), (*VIPPort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VIPPort_To_v1alpha1_VIPPort(a.(*sdn.VIPPort), b.(*VIPPort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPC)(nil), (*sdn.VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPC_To_sdn_VPC(a.(*VPC), b.(*sdn.VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPC)(nil), (*VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPC_To_v1alpha1_VPC(a.(*sdn.VPC), b.(*VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCBinding)(nil), (*sdn.VPCBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCBinding_To_sdn_VPCBinding(a.(*VPCBinding), b.(*sdn.VPCBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCBinding)(nil), (*VPCBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCBinding_To_v1alpha1_VPCBinding(a.(*sdn.VPCBinding), b.(*VPCBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCBindingList)(nil), (*sdn.VPCBindingList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(a.(*VPCBindingList), b.(*sdn.VPCBindingList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCBindingList)(nil), (*VPCBindingList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(a.(*sdn.VPCBindingList), b.(*VPCBindingList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCBindingSpec)(nil), (*sdn.VPCBindingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(a.(*VPCBindingSpec), b.(*sdn.VPCBindingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCBindingSpec)(nil), (*VPCBindingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(a.(*sdn.VPCBindingSpec), b.(*VPCBindingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCGateway)(nil), (*sdn.VPCGateway)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCGateway_To_sdn_VPCGateway(a.(*VPCGateway), b.(*sdn.VPCGateway), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCGateway)(nil), (*VPCGateway)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCGateway_To_v1alpha1_VPCGateway(a.(*sdn.VPCGateway), b.(*VPCGateway), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCGatewayIngress)(nil), (*sdn.VPCGatewayIngress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCGatewayIngress_To_sdn_VPCGatewayIngress(a.(*VPCGatewayIngress), b.(*sdn.VPCGatewayIngress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCGatewayIngress)(nil), (*VPCGatewayIngress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCGatewayIngress_To_v1alpha1_VPCGatewayIngress(a.(*sdn.VPCGatewayIngress), b.(*VPCGatewayIngress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCGatewayList)(nil), (*sdn.VPCGatewayList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCGatewayList_To_sdn_VPCGatewayList(a.(*VPCGatewayList), b.(*sdn.VPCGatewayList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCGatewayList)(nil), (*VPCGatewayList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCGatewayList_To_v1alpha1_VPCGatewayList(a.(*sdn.VPCGatewayList), b.(*VPCGatewayList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCGatewayNAT)(nil), (*sdn.VPCGatewayNAT)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCGatewayNAT_To_sdn_VPCGatewayNAT(a.(*VPCGatewayNAT), b.(*sdn.VPCGatewayNAT), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCGatewayNAT)(nil), (*VPCGatewayNAT)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCGatewayNAT_To_v1alpha1_VPCGatewayNAT(a.(*sdn.VPCGatewayNAT), b.(*VPCGatewayNAT), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCGatewaySpec)(nil), (*sdn.VPCGatewaySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCGatewaySpec_To_sdn_VPCGatewaySpec(a.(*VPCGatewaySpec), b.(*sdn.VPCGatewaySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCGatewaySpec)(nil), (*VPCGatewaySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCGatewaySpec_To_v1alpha1_VPCGatewaySpec(a.(*sdn.VPCGatewaySpec), b.(*VPCGatewaySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCGatewayStatus)(nil), (*sdn.VPCGatewayStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCGatewayStatus_To_sdn_VPCGatewayStatus(a.(*VPCGatewayStatus), b.(*sdn.VPCGatewayStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCGatewayStatus)(nil), (*VPCGatewayStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCGatewayStatus_To_v1alpha1_VPCGatewayStatus(a.(*sdn.VPCGatewayStatus), b.(*VPCGatewayStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCList)(nil), (*sdn.VPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCList_To_sdn_VPCList(a.(*VPCList), b.(*sdn.VPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCList)(nil), (*VPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCList_To_v1alpha1_VPCList(a.(*sdn.VPCList), b.(*VPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeering)(nil), (*sdn.VPCPeering)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeering_To_sdn_VPCPeering(a.(*VPCPeering), b.(*sdn.VPCPeering), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeering)(nil), (*VPCPeering)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeering_To_v1alpha1_VPCPeering(a.(*sdn.VPCPeering), b.(*VPCPeering), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeeringList)(nil), (*sdn.VPCPeeringList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(a.(*VPCPeeringList), b.(*sdn.VPCPeeringList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeeringList)(nil), (*VPCPeeringList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(a.(*sdn.VPCPeeringList), b.(*VPCPeeringList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeeringSpec)(nil), (*sdn.VPCPeeringSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(a.(*VPCPeeringSpec), b.(*sdn.VPCPeeringSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeeringSpec)(nil), (*VPCPeeringSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(a.(*sdn.VPCPeeringSpec), b.(*VPCPeeringSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCPeeringStatus)(nil), (*sdn.VPCPeeringStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(a.(*VPCPeeringStatus), b.(*sdn.VPCPeeringStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCPeeringStatus)(nil), (*VPCPeeringStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(a.(*sdn.VPCPeeringStatus), b.(*VPCPeeringStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCRef)(nil), (*sdn.VPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCRef_To_sdn_VPCRef(a.(*VPCRef), b.(*sdn.VPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCRef)(nil), (*VPCRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCRef_To_v1alpha1_VPCRef(a.(*sdn.VPCRef), b.(*VPCRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCSpec)(nil), (*sdn.VPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(a.(*VPCSpec), b.(*sdn.VPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCSpec)(nil), (*VPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(a.(*sdn.VPCSpec), b.(*VPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCStatus)(nil), (*sdn.VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(a.(*VPCStatus), b.(*sdn.VPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCStatus)(nil), (*VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(a.(*sdn.VPCStatus), b.(*VPCStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_FloatingIP_To_sdn_FloatingIP(in *FloatingIP, out *sdn.FloatingIP, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FloatingIPSpec_To_sdn_FloatingIPSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FloatingIPStatus_To_sdn_FloatingIPStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_FloatingIP_To_sdn_FloatingIP is an autogenerated conversion function.
func Convert_v1alpha1_FloatingIP_To_sdn_FloatingIP(in *FloatingIP, out *sdn.FloatingIP, s conversion.Scope) error {
	return autoConvert_v1alpha1_FloatingIP_To_sdn_FloatingIP(in, out, s)
}

func autoConvert_sdn_FloatingIP_To_v1alpha1_FloatingIP(in *sdn.FloatingIP, out *FloatingIP, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_FloatingIPSpec_To_v1alpha1_FloatingIPSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_FloatingIPStatus_To_v1alpha1_FloatingIPStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_FloatingIP_To_v1alpha1_FloatingIP is an autogenerated conversion function.
func Convert_sdn_FloatingIP_To_v1alpha1_FloatingIP(in *sdn.FloatingIP, out *FloatingIP, s conversion.Scope) error {
	return autoConvert_sdn_FloatingIP_To_v1alpha1_FloatingIP(in, out, s)
}

func autoConvert_v1alpha1_FloatingIPList_To_sdn_FloatingIPList(in *FloatingIPList, out *sdn.FloatingIPList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.FloatingIP)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_FloatingIPList_To_sdn_FloatingIPList is an autogenerated conversion function.
func Convert_v1alpha1_FloatingIPList_To_sdn_FloatingIPList(in *FloatingIPList, out *sdn.FloatingIPList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FloatingIPList_To_sdn_FloatingIPList(in, out, s)
}

func autoConvert_sdn_FloatingIPList_To_v1alpha1_FloatingIPList(in *sdn.FloatingIPList, out *FloatingIPList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]FloatingIP)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_FloatingIPList_To_v1alpha1_FloatingIPList is an autogenerated conversion function.
func Convert_sdn_FloatingIPList_To_v1alpha1_FloatingIPList(in *sdn.FloatingIPList, out *FloatingIPList, s conversion.Scope) error {
	return autoConvert_sdn_FloatingIPList_To_v1alpha1_FloatingIPList(in, out, s)
}

func autoConvert_v1alpha1_FloatingIPSpec_To_sdn_FloatingIPSpec(in *FloatingIPSpec, out *sdn.FloatingIPSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.Target = in.Target
	out.LoadBalancerClass = in.LoadBalancerClass
	return nil
}

// Convert_v1alpha1_FloatingIPSpec_To_sdn_FloatingIPSpec is an autogenerated conversion function.
func Convert_v1alpha1_FloatingIPSpec_To_sdn_FloatingIPSpec(in *FloatingIPSpec, out *sdn.FloatingIPSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FloatingIPSpec_To_sdn_FloatingIPSpec(in, out, s)
}

func autoConvert_sdn_FloatingIPSpec_To_v1alpha1_FloatingIPSpec(in *sdn.FloatingIPSpec, out *FloatingIPSpec, s conversion.Scope) error {
	if err := Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.Target = in.Target
	out.LoadBalancerClass = in.LoadBalancerClass
	return nil
}

// Convert_sdn_FloatingIPSpec_To_v1alpha1_FloatingIPSpec is an autogenerated conversion function.
func Convert_sdn_FloatingIPSpec_To_v1alpha1_FloatingIPSpec(in *sdn.FloatingIPSpec, out *FloatingIPSpec, s conversion.Scope) error {
	return autoConvert_sdn_FloatingIPSpec_To_v1alpha1_FloatingIPSpec(in, out, s)
}

func autoConvert_v1alpha1_FloatingIPStatus_To_sdn_FloatingIPStatus(in *FloatingIPStatus, out *sdn.FloatingIPStatus, s conversion.Scope) error {
	out.Address = in.Address
	out.Phase = sdn.FloatingIPPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_FloatingIPStatus_To_sdn_FloatingIPStatus is an autogenerated conversion function.
func Convert_v1alpha1_FloatingIPStatus_To_sdn_FloatingIPStatus(in *FloatingIPStatus, out *sdn.FloatingIPStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_FloatingIPStatus_To_sdn_FloatingIPStatus(in, out, s)
}

func autoConvert_sdn_FloatingIPStatus_To_v1alpha1_FloatingIPStatus(in *sdn.FloatingIPStatus, out *FloatingIPStatus, s conversion.Scope) error {
	out.Address = in.Address
	out.Phase = FloatingIPPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_FloatingIPStatus_To_v1alpha1_FloatingIPStatus is an autogenerated conversion function.
func Convert_sdn_FloatingIPStatus_To_v1alpha1_FloatingIPStatus(in *sdn.FloatingIPStatus, out *FloatingIPStatus, s conversion.Scope) error {
	return autoConvert_sdn_FloatingIPStatus_To_v1alpha1_FloatingIPStatus(in, out, s)
}

func autoConvert_v1alpha1_HostFirewall_To_sdn_HostFirewall(in *HostFirewall, out *sdn.HostFirewall, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_HostFirewallSpec_To_sdn_HostFirewallSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_HostFirewallStatus_To_sdn_HostFirewallStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_HostFirewall_To_sdn_HostFirewall is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewall_To_sdn_HostFirewall(in *HostFirewall, out *sdn.HostFirewall, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewall_To_sdn_HostFirewall(in, out, s)
}

func autoConvert_sdn_HostFirewall_To_v1alpha1_HostFirewall(in *sdn.HostFirewall, out *HostFirewall, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_HostFirewallSpec_To_v1alpha1_HostFirewallSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_HostFirewallStatus_To_v1alpha1_HostFirewallStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_HostFirewall_To_v1alpha1_HostFirewall is an autogenerated conversion function.
func Convert_sdn_HostFirewall_To_v1alpha1_HostFirewall(in *sdn.HostFirewall, out *HostFirewall, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewall_To_v1alpha1_HostFirewall(in, out, s)
}

func autoConvert_v1alpha1_HostFirewallEgressRule_To_sdn_HostFirewallEgressRule(in *HostFirewallEgressRule, out *sdn.HostFirewallEgressRule, s conversion.Scope) error {
	out.To = *(*[]sdn.HostFirewallPeer)(unsafe.Pointer(&in.To))
	out.Ports = *(*[]sdn.HostFirewallPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_v1alpha1_HostFirewallEgressRule_To_sdn_HostFirewallEgressRule is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewallEgressRule_To_sdn_HostFirewallEgressRule(in *HostFirewallEgressRule, out *sdn.HostFirewallEgressRule, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewallEgressRule_To_sdn_HostFirewallEgressRule(in, out, s)
}

func autoConvert_sdn_HostFirewallEgressRule_To_v1alpha1_HostFirewallEgressRule(in *sdn.HostFirewallEgressRule, out *HostFirewallEgressRule, s conversion.Scope) error {
	out.To = *(*[]HostFirewallPeer)(unsafe.Pointer(&in.To))
	out.Ports = *(*[]HostFirewallPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_sdn_HostFirewallEgressRule_To_v1alpha1_HostFirewallEgressRule is an autogenerated conversion function.
func Convert_sdn_HostFirewallEgressRule_To_v1alpha1_HostFirewallEgressRule(in *sdn.HostFirewallEgressRule, out *HostFirewallEgressRule, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewallEgressRule_To_v1alpha1_HostFirewallEgressRule(in, out, s)
}

func autoConvert_v1alpha1_HostFirewallList_To_sdn_HostFirewallList(in *HostFirewallList, out *sdn.HostFirewallList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.HostFirewall)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_HostFirewallList_To_sdn_HostFirewallList is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewallList_To_sdn_HostFirewallList(in *HostFirewallList, out *sdn.HostFirewallList, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewallList_To_sdn_HostFirewallList(in, out, s)
}

func autoConvert_sdn_HostFirewallList_To_v1alpha1_HostFirewallList(in *sdn.HostFirewallList, out *HostFirewallList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HostFirewall)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_HostFirewallList_To_v1alpha1_HostFirewallList is an autogenerated conversion function.
func Convert_sdn_HostFirewallList_To_v1alpha1_HostFirewallList(in *sdn.HostFirewallList, out *HostFirewallList, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewallList_To_v1alpha1_HostFirewallList(in, out, s)
}

func autoConvert_v1alpha1_HostFirewallPeer_To_sdn_HostFirewallPeer(in *HostFirewallPeer, out *sdn.HostFirewallPeer, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.Except = *(*[]string)(unsafe.Pointer(&in.Except))
	return nil
}

// Convert_v1alpha1_HostFirewallPeer_To_sdn_HostFirewallPeer is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewallPeer_To_sdn_HostFirewallPeer(in *HostFirewallPeer, out *sdn.HostFirewallPeer, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewallPeer_To_sdn_HostFirewallPeer(in, out, s)
}

func autoConvert_sdn_HostFirewallPeer_To_v1alpha1_HostFirewallPeer(in *sdn.HostFirewallPeer, out *HostFirewallPeer, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.Except = *(*[]string)(unsafe.Pointer(&in.Except))
	return nil
}

// Convert_sdn_HostFirewallPeer_To_v1alpha1_HostFirewallPeer is an autogenerated conversion function.
func Convert_sdn_HostFirewallPeer_To_v1alpha1_HostFirewallPeer(in *sdn.HostFirewallPeer, out *HostFirewallPeer, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewallPeer_To_v1alpha1_HostFirewallPeer(in, out, s)
}

func autoConvert_v1alpha1_HostFirewallPort_To_sdn_HostFirewallPort(in *HostFirewallPort, out *sdn.HostFirewallPort, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.EndPort = in.EndPort
	return nil
}

// Convert_v1alpha1_HostFirewallPort_To_sdn_HostFirewallPort is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewallPort_To_sdn_HostFirewallPort(in *HostFirewallPort, out *sdn.HostFirewallPort, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewallPort_To_sdn_HostFirewallPort(in, out, s)
}

func autoConvert_sdn_HostFirewallPort_To_v1alpha1_HostFirewallPort(in *sdn.HostFirewallPort, out *HostFirewallPort, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.EndPort = in.EndPort
	return nil
}

// Convert_sdn_HostFirewallPort_To_v1alpha1_HostFirewallPort is an autogenerated conversion function.
func Convert_sdn_HostFirewallPort_To_v1alpha1_HostFirewallPort(in *sdn.HostFirewallPort, out *HostFirewallPort, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewallPort_To_v1alpha1_HostFirewallPort(in, out, s)
}

func autoConvert_v1alpha1_HostFirewallRule_To_sdn_HostFirewallRule(in *HostFirewallRule, out *sdn.HostFirewallRule, s conversion.Scope) error {
	out.From = *(*[]sdn.HostFirewallPeer)(unsafe.Pointer(&in.From))
	out.Ports = *(*[]sdn.HostFirewallPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_v1alpha1_HostFirewallRule_To_sdn_HostFirewallRule is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewallRule_To_sdn_HostFirewallRule(in *HostFirewallRule, out *sdn.HostFirewallRule, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewallRule_To_sdn_HostFirewallRule(in, out, s)
}

func autoConvert_sdn_HostFirewallRule_To_v1alpha1_HostFirewallRule(in *sdn.HostFirewallRule, out *HostFirewallRule, s conversion.Scope) error {
	out.From = *(*[]HostFirewallPeer)(unsafe.Pointer(&in.From))
	out.Ports = *(*[]HostFirewallPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_sdn_HostFirewallRule_To_v1alpha1_HostFirewallRule is an autogenerated conversion function.
func Convert_sdn_HostFirewallRule_To_v1alpha1_HostFirewallRule(in *sdn.HostFirewallRule, out *HostFirewallRule, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewallRule_To_v1alpha1_HostFirewallRule(in, out, s)
}

func autoConvert_v1alpha1_HostFirewallSpec_To_sdn_HostFirewallSpec(in *HostFirewallSpec, out *sdn.HostFirewallSpec, s conversion.Scope) error {
	out.NodeSelector = in.NodeSelector
	out.PolicyTypes = *(*[]sdn.HostFirewallPolicyType)(unsafe.Pointer(&in.PolicyTypes))
	out.Ingress = *(*[]sdn.HostFirewallRule)(unsafe.Pointer(&in.Ingress))
	out.Egress = *(*[]sdn.HostFirewallEgressRule)(unsafe.Pointer(&in.Egress))
	return nil
}

// Convert_v1alpha1_HostFirewallSpec_To_sdn_HostFirewallSpec is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewallSpec_To_sdn_HostFirewallSpec(in *HostFirewallSpec, out *sdn.HostFirewallSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewallSpec_To_sdn_HostFirewallSpec(in, out, s)
}

func autoConvert_sdn_HostFirewallSpec_To_v1alpha1_HostFirewallSpec(in *sdn.HostFirewallSpec, out *HostFirewallSpec, s conversion.Scope) error {
	out.NodeSelector = in.NodeSelector
	out.PolicyTypes = *(*[]HostFirewallPolicyType)(unsafe.Pointer(&in.PolicyTypes))
	out.Ingress = *(*[]HostFirewallRule)(unsafe.Pointer(&in.Ingress))
	out.Egress = *(*[]HostFirewallEgressRule)(unsafe.Pointer(&in.Egress))
	return nil
}

// Convert_sdn_HostFirewallSpec_To_v1alpha1_HostFirewallSpec is an autogenerated conversion function.
func Convert_sdn_HostFirewallSpec_To_v1alpha1_HostFirewallSpec(in *sdn.HostFirewallSpec, out *HostFirewallSpec, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewallSpec_To_v1alpha1_HostFirewallSpec(in, out, s)
}

func autoConvert_v1alpha1_HostFirewallStatus_To_sdn_HostFirewallStatus(in *HostFirewallStatus, out *sdn.HostFirewallStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_HostFirewallStatus_To_sdn_HostFirewallStatus is an autogenerated conversion function.
func Convert_v1alpha1_HostFirewallStatus_To_sdn_HostFirewallStatus(in *HostFirewallStatus, out *sdn.HostFirewallStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostFirewallStatus_To_sdn_HostFirewallStatus(in, out, s)
}

func autoConvert_sdn_HostFirewallStatus_To_v1alpha1_HostFirewallStatus(in *sdn.HostFirewallStatus, out *HostFirewallStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_HostFirewallStatus_To_v1alpha1_HostFirewallStatus is an autogenerated conversion function.
func Convert_sdn_HostFirewallStatus_To_v1alpha1_HostFirewallStatus(in *sdn.HostFirewallStatus, out *HostFirewallStatus, s conversion.Scope) error {
	return autoConvert_sdn_HostFirewallStatus_To_v1alpha1_HostFirewallStatus(in, out, s)
}

func autoConvert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(in *LocalVPCRef, out *sdn.LocalVPCRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef is an autogenerated conversion function.
func Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(in *LocalVPCRef, out *sdn.LocalVPCRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(in, out, s)
}

func autoConvert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(in *sdn.LocalVPCRef, out *LocalVPCRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef is an autogenerated conversion function.
func Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(in *sdn.LocalVPCRef, out *LocalVPCRef, s conversion.Scope) error {
	return autoConvert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(in, out, s)
}

func autoConvert_v1alpha1_Port_To_sdn_Port(in *Port, out *sdn.Port, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PortSpec_To_sdn_PortSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PortStatus_To_sdn_PortStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Port_To_sdn_Port is an autogenerated conversion function.
func Convert_v1alpha1_Port_To_sdn_Port(in *Port, out *sdn.Port, s conversion.Scope) error {
	return autoConvert_v1alpha1_Port_To_sdn_Port(in, out, s)
}

func autoConvert_sdn_Port_To_v1alpha1_Port(in *sdn.Port, out *Port, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_PortSpec_To_v1alpha1_PortSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_PortStatus_To_v1alpha1_PortStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_Port_To_v1alpha1_Port is an autogenerated conversion function.
func Convert_sdn_Port_To_v1alpha1_Port(in *sdn.Port, out *Port, s conversion.Scope) error {
	return autoConvert_sdn_Port_To_v1alpha1_Port(in, out, s)
}

func autoConvert_v1alpha1_PortList_To_sdn_PortList(in *PortList, out *sdn.PortList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.Port)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PortList_To_sdn_PortList is an autogenerated conversion function.
func Convert_v1alpha1_PortList_To_sdn_PortList(in *PortList, out *sdn.PortList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PortList_To_sdn_PortList(in, out, s)
}

func autoConvert_sdn_PortList_To_v1alpha1_PortList(in *sdn.PortList, out *PortList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Port)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_PortList_To_v1alpha1_PortList is an autogenerated conversion function.
func Convert_sdn_PortList_To_v1alpha1_PortList(in *sdn.PortList, out *PortList, s conversion.Scope) error {
	return autoConvert_sdn_PortList_To_v1alpha1_PortList(in, out, s)
}

func autoConvert_v1alpha1_PortSpec_To_sdn_PortSpec(in *PortSpec, out *sdn.PortSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPCRef_To_sdn_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.IP = in.IP
	out.MAC = in.MAC
	out.Node = in.Node
	out.NodeIP = in.NodeIP
	out.PodNamespace = in.PodNamespace
	out.PodName = in.PodName
	out.Gateway = in.Gateway
	return nil
}

// Convert_v1alpha1_PortSpec_To_sdn_PortSpec is an autogenerated conversion function.
func Convert_v1alpha1_PortSpec_To_sdn_PortSpec(in *PortSpec, out *sdn.PortSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PortSpec_To_sdn_PortSpec(in, out, s)
}

func autoConvert_sdn_PortSpec_To_v1alpha1_PortSpec(in *sdn.PortSpec, out *PortSpec, s conversion.Scope) error {
	if err := Convert_sdn_VPCRef_To_v1alpha1_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.IP = in.IP
	out.MAC = in.MAC
	out.Node = in.Node
	out.NodeIP = in.NodeIP
	out.PodNamespace = in.PodNamespace
	out.PodName = in.PodName
	out.Gateway = in.Gateway
	return nil
}

// Convert_sdn_PortSpec_To_v1alpha1_PortSpec is an autogenerated conversion function.
func Convert_sdn_PortSpec_To_v1alpha1_PortSpec(in *sdn.PortSpec, out *PortSpec, s conversion.Scope) error {
	return autoConvert_sdn_PortSpec_To_v1alpha1_PortSpec(in, out, s)
}

func autoConvert_v1alpha1_PortStatus_To_sdn_PortStatus(in *PortStatus, out *sdn.PortStatus, s conversion.Scope) error {
	out.Groups = *(*[]int32)(unsafe.Pointer(&in.Groups))
	return nil
}

// Convert_v1alpha1_PortStatus_To_sdn_PortStatus is an autogenerated conversion function.
func Convert_v1alpha1_PortStatus_To_sdn_PortStatus(in *PortStatus, out *sdn.PortStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PortStatus_To_sdn_PortStatus(in, out, s)
}

func autoConvert_sdn_PortStatus_To_v1alpha1_PortStatus(in *sdn.PortStatus, out *PortStatus, s conversion.Scope) error {
	out.Groups = *(*[]int32)(unsafe.Pointer(&in.Groups))
	return nil
}

// Convert_sdn_PortStatus_To_v1alpha1_PortStatus is an autogenerated conversion function.
func Convert_sdn_PortStatus_To_v1alpha1_PortStatus(in *sdn.PortStatus, out *PortStatus, s conversion.Scope) error {
	return autoConvert_sdn_PortStatus_To_v1alpha1_PortStatus(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroup_To_sdn_SecurityGroup(in *SecurityGroup, out *sdn.SecurityGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SecurityGroupSpec_To_sdn_SecurityGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SecurityGroupStatus_To_sdn_SecurityGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SecurityGroup_To_sdn_SecurityGroup is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroup_To_sdn_SecurityGroup(in *SecurityGroup, out *sdn.SecurityGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroup_To_sdn_SecurityGroup(in, out, s)
}

func autoConvert_sdn_SecurityGroup_To_v1alpha1_SecurityGroup(in *sdn.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_SecurityGroupSpec_To_v1alpha1_SecurityGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_SecurityGroupStatus_To_v1alpha1_SecurityGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_SecurityGroup_To_v1alpha1_SecurityGroup is an autogenerated conversion function.
func Convert_sdn_SecurityGroup_To_v1alpha1_SecurityGroup(in *sdn.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroup_To_v1alpha1_SecurityGroup(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroupEgressRule_To_sdn_SecurityGroupEgressRule(in *SecurityGroupEgressRule, out *sdn.SecurityGroupEgressRule, s conversion.Scope) error {
	if err := Convert_v1alpha1_SecurityGroupPeer_To_sdn_SecurityGroupPeer(&in.To, &out.To, s); err != nil {
		return err
	}
	out.Ports = *(*[]sdn.SecurityGroupPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_v1alpha1_SecurityGroupEgressRule_To_sdn_SecurityGroupEgressRule is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroupEgressRule_To_sdn_SecurityGroupEgressRule(in *SecurityGroupEgressRule, out *sdn.SecurityGroupEgressRule, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroupEgressRule_To_sdn_SecurityGroupEgressRule(in, out, s)
}

func autoConvert_sdn_SecurityGroupEgressRule_To_v1alpha1_SecurityGroupEgressRule(in *sdn.SecurityGroupEgressRule, out *SecurityGroupEgressRule, s conversion.Scope) error {
	if err := Convert_sdn_SecurityGroupPeer_To_v1alpha1_SecurityGroupPeer(&in.To, &out.To, s); err != nil {
		return err
	}
	out.Ports = *(*[]SecurityGroupPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_sdn_SecurityGroupEgressRule_To_v1alpha1_SecurityGroupEgressRule is an autogenerated conversion function.
func Convert_sdn_SecurityGroupEgressRule_To_v1alpha1_SecurityGroupEgressRule(in *sdn.SecurityGroupEgressRule, out *SecurityGroupEgressRule, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroupEgressRule_To_v1alpha1_SecurityGroupEgressRule(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroupList_To_sdn_SecurityGroupList(in *SecurityGroupList, out *sdn.SecurityGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.SecurityGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SecurityGroupList_To_sdn_SecurityGroupList is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroupList_To_sdn_SecurityGroupList(in *SecurityGroupList, out *sdn.SecurityGroupList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroupList_To_sdn_SecurityGroupList(in, out, s)
}

func autoConvert_sdn_SecurityGroupList_To_v1alpha1_SecurityGroupList(in *sdn.SecurityGroupList, out *SecurityGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SecurityGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_SecurityGroupList_To_v1alpha1_SecurityGroupList is an autogenerated conversion function.
func Convert_sdn_SecurityGroupList_To_v1alpha1_SecurityGroupList(in *sdn.SecurityGroupList, out *SecurityGroupList, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroupList_To_v1alpha1_SecurityGroupList(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroupPeer_To_sdn_SecurityGroupPeer(in *SecurityGroupPeer, out *sdn.SecurityGroupPeer, s conversion.Scope) error {
	out.Group = in.Group
	out.VPC = (*sdn.VPCRef)(unsafe.Pointer(in.VPC))
	out.CIDR = in.CIDR
	return nil
}

// Convert_v1alpha1_SecurityGroupPeer_To_sdn_SecurityGroupPeer is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroupPeer_To_sdn_SecurityGroupPeer(in *SecurityGroupPeer, out *sdn.SecurityGroupPeer, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroupPeer_To_sdn_SecurityGroupPeer(in, out, s)
}

func autoConvert_sdn_SecurityGroupPeer_To_v1alpha1_SecurityGroupPeer(in *sdn.SecurityGroupPeer, out *SecurityGroupPeer, s conversion.Scope) error {
	out.Group = in.Group
	out.VPC = (*VPCRef)(unsafe.Pointer(in.VPC))
	out.CIDR = in.CIDR
	return nil
}

// Convert_sdn_SecurityGroupPeer_To_v1alpha1_SecurityGroupPeer is an autogenerated conversion function.
func Convert_sdn_SecurityGroupPeer_To_v1alpha1_SecurityGroupPeer(in *sdn.SecurityGroupPeer, out *SecurityGroupPeer, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroupPeer_To_v1alpha1_SecurityGroupPeer(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroupPort_To_sdn_SecurityGroupPort(in *SecurityGroupPort, out *sdn.SecurityGroupPort, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_SecurityGroupPort_To_sdn_SecurityGroupPort is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroupPort_To_sdn_SecurityGroupPort(in *SecurityGroupPort, out *sdn.SecurityGroupPort, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroupPort_To_sdn_SecurityGroupPort(in, out, s)
}

func autoConvert_sdn_SecurityGroupPort_To_v1alpha1_SecurityGroupPort(in *sdn.SecurityGroupPort, out *SecurityGroupPort, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Port = in.Port
	return nil
}

// Convert_sdn_SecurityGroupPort_To_v1alpha1_SecurityGroupPort is an autogenerated conversion function.
func Convert_sdn_SecurityGroupPort_To_v1alpha1_SecurityGroupPort(in *sdn.SecurityGroupPort, out *SecurityGroupPort, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroupPort_To_v1alpha1_SecurityGroupPort(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroupRule_To_sdn_SecurityGroupRule(in *SecurityGroupRule, out *sdn.SecurityGroupRule, s conversion.Scope) error {
	if err := Convert_v1alpha1_SecurityGroupPeer_To_sdn_SecurityGroupPeer(&in.From, &out.From, s); err != nil {
		return err
	}
	out.Ports = *(*[]sdn.SecurityGroupPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_v1alpha1_SecurityGroupRule_To_sdn_SecurityGroupRule is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroupRule_To_sdn_SecurityGroupRule(in *SecurityGroupRule, out *sdn.SecurityGroupRule, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroupRule_To_sdn_SecurityGroupRule(in, out, s)
}

func autoConvert_sdn_SecurityGroupRule_To_v1alpha1_SecurityGroupRule(in *sdn.SecurityGroupRule, out *SecurityGroupRule, s conversion.Scope) error {
	if err := Convert_sdn_SecurityGroupPeer_To_v1alpha1_SecurityGroupPeer(&in.From, &out.From, s); err != nil {
		return err
	}
	out.Ports = *(*[]SecurityGroupPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_sdn_SecurityGroupRule_To_v1alpha1_SecurityGroupRule is an autogenerated conversion function.
func Convert_sdn_SecurityGroupRule_To_v1alpha1_SecurityGroupRule(in *sdn.SecurityGroupRule, out *SecurityGroupRule, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroupRule_To_v1alpha1_SecurityGroupRule(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroupSpec_To_sdn_SecurityGroupSpec(in *SecurityGroupSpec, out *sdn.SecurityGroupSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.PodSelector = in.PodSelector
	out.Ingress = *(*[]sdn.SecurityGroupRule)(unsafe.Pointer(&in.Ingress))
	out.Egress = *(*[]sdn.SecurityGroupEgressRule)(unsafe.Pointer(&in.Egress))
	return nil
}

// Convert_v1alpha1_SecurityGroupSpec_To_sdn_SecurityGroupSpec is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroupSpec_To_sdn_SecurityGroupSpec(in *SecurityGroupSpec, out *sdn.SecurityGroupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroupSpec_To_sdn_SecurityGroupSpec(in, out, s)
}

func autoConvert_sdn_SecurityGroupSpec_To_v1alpha1_SecurityGroupSpec(in *sdn.SecurityGroupSpec, out *SecurityGroupSpec, s conversion.Scope) error {
	if err := Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.PodSelector = in.PodSelector
	out.Ingress = *(*[]SecurityGroupRule)(unsafe.Pointer(&in.Ingress))
	out.Egress = *(*[]SecurityGroupEgressRule)(unsafe.Pointer(&in.Egress))
	return nil
}

// Convert_sdn_SecurityGroupSpec_To_v1alpha1_SecurityGroupSpec is an autogenerated conversion function.
func Convert_sdn_SecurityGroupSpec_To_v1alpha1_SecurityGroupSpec(in *sdn.SecurityGroupSpec, out *SecurityGroupSpec, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroupSpec_To_v1alpha1_SecurityGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroupStatus_To_sdn_SecurityGroupStatus(in *SecurityGroupStatus, out *sdn.SecurityGroupStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Phase = sdn.SecurityGroupPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_SecurityGroupStatus_To_sdn_SecurityGroupStatus is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroupStatus_To_sdn_SecurityGroupStatus(in *SecurityGroupStatus, out *sdn.SecurityGroupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroupStatus_To_sdn_SecurityGroupStatus(in, out, s)
}

func autoConvert_sdn_SecurityGroupStatus_To_v1alpha1_SecurityGroupStatus(in *sdn.SecurityGroupStatus, out *SecurityGroupStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.Phase = SecurityGroupPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_SecurityGroupStatus_To_v1alpha1_SecurityGroupStatus is an autogenerated conversion function.
func Convert_sdn_SecurityGroupStatus_To_v1alpha1_SecurityGroupStatus(in *sdn.SecurityGroupStatus, out *SecurityGroupStatus, s conversion.Scope) error {
	return autoConvert_sdn_SecurityGroupStatus_To_v1alpha1_SecurityGroupStatus(in, out, s)
}

func autoConvert_v1alpha1_ServiceRef_To_sdn_ServiceRef(in *ServiceRef, out *sdn.ServiceRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ServiceRef_To_sdn_ServiceRef is an autogenerated conversion function.
func Convert_v1alpha1_ServiceRef_To_sdn_ServiceRef(in *ServiceRef, out *sdn.ServiceRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceRef_To_sdn_ServiceRef(in, out, s)
}

func autoConvert_sdn_ServiceRef_To_v1alpha1_ServiceRef(in *sdn.ServiceRef, out *ServiceRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_sdn_ServiceRef_To_v1alpha1_ServiceRef is an autogenerated conversion function.
func Convert_sdn_ServiceRef_To_v1alpha1_ServiceRef(in *sdn.ServiceRef, out *ServiceRef, s conversion.Scope) error {
	return autoConvert_sdn_ServiceRef_To_v1alpha1_ServiceRef(in, out, s)
}

func autoConvert_v1alpha1_ServiceVIP_To_sdn_ServiceVIP(in *ServiceVIP, out *sdn.ServiceVIP, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ServiceVIPSpec_To_sdn_ServiceVIPSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ServiceVIPStatus_To_sdn_ServiceVIPStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceVIP_To_sdn_ServiceVIP is an autogenerated conversion function.
func Convert_v1alpha1_ServiceVIP_To_sdn_ServiceVIP(in *ServiceVIP, out *sdn.ServiceVIP, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceVIP_To_sdn_ServiceVIP(in, out, s)
}

func autoConvert_sdn_ServiceVIP_To_v1alpha1_ServiceVIP(in *sdn.ServiceVIP, out *ServiceVIP, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_ServiceVIPSpec_To_v1alpha1_ServiceVIPSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_ServiceVIPStatus_To_v1alpha1_ServiceVIPStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_ServiceVIP_To_v1alpha1_ServiceVIP is an autogenerated conversion function.
func Convert_sdn_ServiceVIP_To_v1alpha1_ServiceVIP(in *sdn.ServiceVIP, out *ServiceVIP, s conversion.Scope) error {
	return autoConvert_sdn_ServiceVIP_To_v1alpha1_ServiceVIP(in, out, s)
}

func autoConvert_v1alpha1_ServiceVIPList_To_sdn_ServiceVIPList(in *ServiceVIPList, out *sdn.ServiceVIPList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.ServiceVIP)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ServiceVIPList_To_sdn_ServiceVIPList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceVIPList_To_sdn_ServiceVIPList(in *ServiceVIPList, out *sdn.ServiceVIPList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceVIPList_To_sdn_ServiceVIPList(in, out, s)
}

func autoConvert_sdn_ServiceVIPList_To_v1alpha1_ServiceVIPList(in *sdn.ServiceVIPList, out *ServiceVIPList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ServiceVIP)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_ServiceVIPList_To_v1alpha1_ServiceVIPList is an autogenerated conversion function.
func Convert_sdn_ServiceVIPList_To_v1alpha1_ServiceVIPList(in *sdn.ServiceVIPList, out *ServiceVIPList, s conversion.Scope) error {
	return autoConvert_sdn_ServiceVIPList_To_v1alpha1_ServiceVIPList(in, out, s)
}

func autoConvert_v1alpha1_ServiceVIPSpec_To_sdn_ServiceVIPSpec(in *ServiceVIPSpec, out *sdn.ServiceVIPSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPCRef_To_sdn_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.IP = in.IP
	if err := Convert_v1alpha1_ServiceRef_To_sdn_ServiceRef(&in.ServiceRef, &out.ServiceRef, s); err != nil {
		return err
	}
	out.Ports = *(*[]sdn.VIPPort)(unsafe.Pointer(&in.Ports))
	out.SessionAffinity = in.SessionAffinity
	return nil
}

// Convert_v1alpha1_ServiceVIPSpec_To_sdn_ServiceVIPSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServiceVIPSpec_To_sdn_ServiceVIPSpec(in *ServiceVIPSpec, out *sdn.ServiceVIPSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceVIPSpec_To_sdn_ServiceVIPSpec(in, out, s)
}

func autoConvert_sdn_ServiceVIPSpec_To_v1alpha1_ServiceVIPSpec(in *sdn.ServiceVIPSpec, out *ServiceVIPSpec, s conversion.Scope) error {
	if err := Convert_sdn_VPCRef_To_v1alpha1_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.IP = in.IP
	if err := Convert_sdn_ServiceRef_To_v1alpha1_ServiceRef(&in.ServiceRef, &out.ServiceRef, s); err != nil {
		return err
	}
	out.Ports = *(*[]VIPPort)(unsafe.Pointer(&in.Ports))
	out.SessionAffinity = in.SessionAffinity
	return nil
}

// Convert_sdn_ServiceVIPSpec_To_v1alpha1_ServiceVIPSpec is an autogenerated conversion function.
func Convert_sdn_ServiceVIPSpec_To_v1alpha1_ServiceVIPSpec(in *sdn.ServiceVIPSpec, out *ServiceVIPSpec, s conversion.Scope) error {
	return autoConvert_sdn_ServiceVIPSpec_To_v1alpha1_ServiceVIPSpec(in, out, s)
}

func autoConvert_v1alpha1_ServiceVIPStatus_To_sdn_ServiceVIPStatus(in *ServiceVIPStatus, out *sdn.ServiceVIPStatus, s conversion.Scope) error {
	out.Backends = *(*[]sdn.VIPBackend)(unsafe.Pointer(&in.Backends))
	out.Phase = sdn.ServiceVIPPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ServiceVIPStatus_To_sdn_ServiceVIPStatus is an autogenerated conversion function.
func Convert_v1alpha1_ServiceVIPStatus_To_sdn_ServiceVIPStatus(in *ServiceVIPStatus, out *sdn.ServiceVIPStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceVIPStatus_To_sdn_ServiceVIPStatus(in, out, s)
}

func autoConvert_sdn_ServiceVIPStatus_To_v1alpha1_ServiceVIPStatus(in *sdn.ServiceVIPStatus, out *ServiceVIPStatus, s conversion.Scope) error {
	out.Backends = *(*[]VIPBackend)(unsafe.Pointer(&in.Backends))
	out.Phase = ServiceVIPPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_ServiceVIPStatus_To_v1alpha1_ServiceVIPStatus is an autogenerated conversion function.
func Convert_sdn_ServiceVIPStatus_To_v1alpha1_ServiceVIPStatus(in *sdn.ServiceVIPStatus, out *ServiceVIPStatus, s conversion.Scope) error {
	return autoConvert_sdn_ServiceVIPStatus_To_v1alpha1_ServiceVIPStatus(in, out, s)
}

func autoConvert_v1alpha1_VIPBackend_To_sdn_VIPBackend(in *VIPBackend, out *sdn.VIPBackend, s conversion.Scope) error {
	out.IP = in.IP
	out.Ports = *(*[]sdn.VIPBackendPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_v1alpha1_VIPBackend_To_sdn_VIPBackend is an autogenerated conversion function.
func Convert_v1alpha1_VIPBackend_To_sdn_VIPBackend(in *VIPBackend, out *sdn.VIPBackend, s conversion.Scope) error {
	return autoConvert_v1alpha1_VIPBackend_To_sdn_VIPBackend(in, out, s)
}

func autoConvert_sdn_VIPBackend_To_v1alpha1_VIPBackend(in *sdn.VIPBackend, out *VIPBackend, s conversion.Scope) error {
	out.IP = in.IP
	out.Ports = *(*[]VIPBackendPort)(unsafe.Pointer(&in.Ports))
	return nil
}

// Convert_sdn_VIPBackend_To_v1alpha1_VIPBackend is an autogenerated conversion function.
func Convert_sdn_VIPBackend_To_v1alpha1_VIPBackend(in *sdn.VIPBackend, out *VIPBackend, s conversion.Scope) error {
	return autoConvert_sdn_VIPBackend_To_v1alpha1_VIPBackend(in, out, s)
}

func autoConvert_v1alpha1_VIPBackendPort_To_sdn_VIPBackendPort(in *VIPBackendPort, out *sdn.VIPBackendPort, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_v1alpha1_VIPBackendPort_To_sdn_VIPBackendPort is an autogenerated conversion function.
func Convert_v1alpha1_VIPBackendPort_To_sdn_VIPBackendPort(in *VIPBackendPort, out *sdn.VIPBackendPort, s conversion.Scope) error {
	return autoConvert_v1alpha1_VIPBackendPort_To_sdn_VIPBackendPort(in, out, s)
}

func autoConvert_sdn_VIPBackendPort_To_v1alpha1_VIPBackendPort(in *sdn.VIPBackendPort, out *VIPBackendPort, s conversion.Scope) error {
	out.Protocol = in.Protocol
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_sdn_VIPBackendPort_To_v1alpha1_VIPBackendPort is an autogenerated conversion function.
func Convert_sdn_VIPBackendPort_To_v1alpha1_VIPBackendPort(in *sdn.VIPBackendPort, out *VIPBackendPort, s conversion.Scope) error {
	return autoConvert_sdn_VIPBackendPort_To_v1alpha1_VIPBackendPort(in, out, s)
}

func autoConvert_v1alpha1_VIPPort_To_sdn_VIPPort(in *VIPPort, out *sdn.VIPPort, s conversion.Scope) error {
	out.Name = in.Name
	out.Protocol = in.Protocol
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_VIPPort_To_sdn_VIPPort is an autogenerated conversion function.
func Convert_v1alpha1_VIPPort_To_sdn_VIPPort(in *VIPPort, out *sdn.VIPPort, s conversion.Scope) error {
	return autoConvert_v1alpha1_VIPPort_To_sdn_VIPPort(in, out, s)
}

func autoConvert_sdn_VIPPort_To_v1alpha1_VIPPort(in *sdn.VIPPort, out *VIPPort, s conversion.Scope) error {
	out.Name = in.Name
	out.Protocol = in.Protocol
	out.Port = in.Port
	return nil
}

// Convert_sdn_VIPPort_To_v1alpha1_VIPPort is an autogenerated conversion function.
func Convert_sdn_VIPPort_To_v1alpha1_VIPPort(in *sdn.VIPPort, out *VIPPort, s conversion.Scope) error {
	return autoConvert_sdn_VIPPort_To_v1alpha1_VIPPort(in, out, s)
}

func autoConvert_v1alpha1_VPC_To_sdn_VPC(in *VPC, out *sdn.VPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPC_To_sdn_VPC is an autogenerated conversion function.
func Convert_v1alpha1_VPC_To_sdn_VPC(in *VPC, out *sdn.VPC, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPC_To_sdn_VPC(in, out, s)
}

func autoConvert_sdn_VPC_To_v1alpha1_VPC(in *sdn.VPC, out *VPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPC_To_v1alpha1_VPC is an autogenerated conversion function.
func Convert_sdn_VPC_To_v1alpha1_VPC(in *sdn.VPC, out *VPC, s conversion.Scope) error {
	return autoConvert_sdn_VPC_To_v1alpha1_VPC(in, out, s)
}

func autoConvert_v1alpha1_VPCBinding_To_sdn_VPCBinding(in *VPCBinding, out *sdn.VPCBinding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCBinding_To_sdn_VPCBinding is an autogenerated conversion function.
func Convert_v1alpha1_VPCBinding_To_sdn_VPCBinding(in *VPCBinding, out *sdn.VPCBinding, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCBinding_To_sdn_VPCBinding(in, out, s)
}

func autoConvert_sdn_VPCBinding_To_v1alpha1_VPCBinding(in *sdn.VPCBinding, out *VPCBinding, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCBinding_To_v1alpha1_VPCBinding is an autogenerated conversion function.
func Convert_sdn_VPCBinding_To_v1alpha1_VPCBinding(in *sdn.VPCBinding, out *VPCBinding, s conversion.Scope) error {
	return autoConvert_sdn_VPCBinding_To_v1alpha1_VPCBinding(in, out, s)
}

func autoConvert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(in *VPCBindingList, out *sdn.VPCBindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPCBinding)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList is an autogenerated conversion function.
func Convert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(in *VPCBindingList, out *sdn.VPCBindingList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCBindingList_To_sdn_VPCBindingList(in, out, s)
}

func autoConvert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(in *sdn.VPCBindingList, out *VPCBindingList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPCBinding)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList is an autogenerated conversion function.
func Convert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(in *sdn.VPCBindingList, out *VPCBindingList, s conversion.Scope) error {
	return autoConvert_sdn_VPCBindingList_To_v1alpha1_VPCBindingList(in, out, s)
}

func autoConvert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(in *VPCBindingSpec, out *sdn.VPCBindingSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPCRef_To_sdn_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(in *VPCBindingSpec, out *sdn.VPCBindingSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCBindingSpec_To_sdn_VPCBindingSpec(in, out, s)
}

func autoConvert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(in *sdn.VPCBindingSpec, out *VPCBindingSpec, s conversion.Scope) error {
	if err := Convert_sdn_VPCRef_To_v1alpha1_VPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec is an autogenerated conversion function.
func Convert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(in *sdn.VPCBindingSpec, out *VPCBindingSpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCBindingSpec_To_v1alpha1_VPCBindingSpec(in, out, s)
}

func autoConvert_v1alpha1_VPCGateway_To_sdn_VPCGateway(in *VPCGateway, out *sdn.VPCGateway, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCGatewaySpec_To_sdn_VPCGatewaySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCGatewayStatus_To_sdn_VPCGatewayStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCGateway_To_sdn_VPCGateway is an autogenerated conversion function.
func Convert_v1alpha1_VPCGateway_To_sdn_VPCGateway(in *VPCGateway, out *sdn.VPCGateway, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCGateway_To_sdn_VPCGateway(in, out, s)
}

func autoConvert_sdn_VPCGateway_To_v1alpha1_VPCGateway(in *sdn.VPCGateway, out *VPCGateway, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCGatewaySpec_To_v1alpha1_VPCGatewaySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCGatewayStatus_To_v1alpha1_VPCGatewayStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCGateway_To_v1alpha1_VPCGateway is an autogenerated conversion function.
func Convert_sdn_VPCGateway_To_v1alpha1_VPCGateway(in *sdn.VPCGateway, out *VPCGateway, s conversion.Scope) error {
	return autoConvert_sdn_VPCGateway_To_v1alpha1_VPCGateway(in, out, s)
}

func autoConvert_v1alpha1_VPCGatewayIngress_To_sdn_VPCGatewayIngress(in *VPCGatewayIngress, out *sdn.VPCGatewayIngress, s conversion.Scope) error {
	out.LoadBalancer = in.LoadBalancer
	return nil
}

// Convert_v1alpha1_VPCGatewayIngress_To_sdn_VPCGatewayIngress is an autogenerated conversion function.
func Convert_v1alpha1_VPCGatewayIngress_To_sdn_VPCGatewayIngress(in *VPCGatewayIngress, out *sdn.VPCGatewayIngress, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCGatewayIngress_To_sdn_VPCGatewayIngress(in, out, s)
}

func autoConvert_sdn_VPCGatewayIngress_To_v1alpha1_VPCGatewayIngress(in *sdn.VPCGatewayIngress, out *VPCGatewayIngress, s conversion.Scope) error {
	out.LoadBalancer = in.LoadBalancer
	return nil
}

// Convert_sdn_VPCGatewayIngress_To_v1alpha1_VPCGatewayIngress is an autogenerated conversion function.
func Convert_sdn_VPCGatewayIngress_To_v1alpha1_VPCGatewayIngress(in *sdn.VPCGatewayIngress, out *VPCGatewayIngress, s conversion.Scope) error {
	return autoConvert_sdn_VPCGatewayIngress_To_v1alpha1_VPCGatewayIngress(in, out, s)
}

func autoConvert_v1alpha1_VPCGatewayList_To_sdn_VPCGatewayList(in *VPCGatewayList, out *sdn.VPCGatewayList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPCGateway)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCGatewayList_To_sdn_VPCGatewayList is an autogenerated conversion function.
func Convert_v1alpha1_VPCGatewayList_To_sdn_VPCGatewayList(in *VPCGatewayList, out *sdn.VPCGatewayList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCGatewayList_To_sdn_VPCGatewayList(in, out, s)
}

func autoConvert_sdn_VPCGatewayList_To_v1alpha1_VPCGatewayList(in *sdn.VPCGatewayList, out *VPCGatewayList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPCGateway)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCGatewayList_To_v1alpha1_VPCGatewayList is an autogenerated conversion function.
func Convert_sdn_VPCGatewayList_To_v1alpha1_VPCGatewayList(in *sdn.VPCGatewayList, out *VPCGatewayList, s conversion.Scope) error {
	return autoConvert_sdn_VPCGatewayList_To_v1alpha1_VPCGatewayList(in, out, s)
}

func autoConvert_v1alpha1_VPCGatewayNAT_To_sdn_VPCGatewayNAT(in *VPCGatewayNAT, out *sdn.VPCGatewayNAT, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_VPCGatewayNAT_To_sdn_VPCGatewayNAT is an autogenerated conversion function.
func Convert_v1alpha1_VPCGatewayNAT_To_sdn_VPCGatewayNAT(in *VPCGatewayNAT, out *sdn.VPCGatewayNAT, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCGatewayNAT_To_sdn_VPCGatewayNAT(in, out, s)
}

func autoConvert_sdn_VPCGatewayNAT_To_v1alpha1_VPCGatewayNAT(in *sdn.VPCGatewayNAT, out *VPCGatewayNAT, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_sdn_VPCGatewayNAT_To_v1alpha1_VPCGatewayNAT is an autogenerated conversion function.
func Convert_sdn_VPCGatewayNAT_To_v1alpha1_VPCGatewayNAT(in *sdn.VPCGatewayNAT, out *VPCGatewayNAT, s conversion.Scope) error {
	return autoConvert_sdn_VPCGatewayNAT_To_v1alpha1_VPCGatewayNAT(in, out, s)
}

func autoConvert_v1alpha1_VPCGatewaySpec_To_sdn_VPCGatewaySpec(in *VPCGatewaySpec, out *sdn.VPCGatewaySpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.LoadBalancerClass = in.LoadBalancerClass
	if err := Convert_v1alpha1_VPCGatewayNAT_To_sdn_VPCGatewayNAT(&in.NAT, &out.NAT, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCGatewayIngress_To_sdn_VPCGatewayIngress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCGatewaySpec_To_sdn_VPCGatewaySpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCGatewaySpec_To_sdn_VPCGatewaySpec(in *VPCGatewaySpec, out *sdn.VPCGatewaySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCGatewaySpec_To_sdn_VPCGatewaySpec(in, out, s)
}

func autoConvert_sdn_VPCGatewaySpec_To_v1alpha1_VPCGatewaySpec(in *sdn.VPCGatewaySpec, out *VPCGatewaySpec, s conversion.Scope) error {
	if err := Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	out.LoadBalancerClass = in.LoadBalancerClass
	if err := Convert_sdn_VPCGatewayNAT_To_v1alpha1_VPCGatewayNAT(&in.NAT, &out.NAT, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCGatewayIngress_To_v1alpha1_VPCGatewayIngress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCGatewaySpec_To_v1alpha1_VPCGatewaySpec is an autogenerated conversion function.
func Convert_sdn_VPCGatewaySpec_To_v1alpha1_VPCGatewaySpec(in *sdn.VPCGatewaySpec, out *VPCGatewaySpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCGatewaySpec_To_v1alpha1_VPCGatewaySpec(in, out, s)
}

func autoConvert_v1alpha1_VPCGatewayStatus_To_sdn_VPCGatewayStatus(in *VPCGatewayStatus, out *sdn.VPCGatewayStatus, s conversion.Scope) error {
	out.NATAddress = in.NATAddress
	out.NATAddress6 = in.NATAddress6
	out.Phase = sdn.VPCGatewayPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_VPCGatewayStatus_To_sdn_VPCGatewayStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCGatewayStatus_To_sdn_VPCGatewayStatus(in *VPCGatewayStatus, out *sdn.VPCGatewayStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCGatewayStatus_To_sdn_VPCGatewayStatus(in, out, s)
}

func autoConvert_sdn_VPCGatewayStatus_To_v1alpha1_VPCGatewayStatus(in *sdn.VPCGatewayStatus, out *VPCGatewayStatus, s conversion.Scope) error {
	out.NATAddress = in.NATAddress
	out.NATAddress6 = in.NATAddress6
	out.Phase = VPCGatewayPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_VPCGatewayStatus_To_v1alpha1_VPCGatewayStatus is an autogenerated conversion function.
func Convert_sdn_VPCGatewayStatus_To_v1alpha1_VPCGatewayStatus(in *sdn.VPCGatewayStatus, out *VPCGatewayStatus, s conversion.Scope) error {
	return autoConvert_sdn_VPCGatewayStatus_To_v1alpha1_VPCGatewayStatus(in, out, s)
}

func autoConvert_v1alpha1_VPCList_To_sdn_VPCList(in *VPCList, out *sdn.VPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCList_To_sdn_VPCList is an autogenerated conversion function.
func Convert_v1alpha1_VPCList_To_sdn_VPCList(in *VPCList, out *sdn.VPCList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCList_To_sdn_VPCList(in, out, s)
}

func autoConvert_sdn_VPCList_To_v1alpha1_VPCList(in *sdn.VPCList, out *VPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCList_To_v1alpha1_VPCList is an autogenerated conversion function.
func Convert_sdn_VPCList_To_v1alpha1_VPCList(in *sdn.VPCList, out *VPCList, s conversion.Scope) error {
	return autoConvert_sdn_VPCList_To_v1alpha1_VPCList(in, out, s)
}

func autoConvert_v1alpha1_VPCPeering_To_sdn_VPCPeering(in *VPCPeering, out *sdn.VPCPeering, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCPeering_To_sdn_VPCPeering is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeering_To_sdn_VPCPeering(in *VPCPeering, out *sdn.VPCPeering, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeering_To_sdn_VPCPeering(in, out, s)
}

func autoConvert_sdn_VPCPeering_To_v1alpha1_VPCPeering(in *sdn.VPCPeering, out *VPCPeering, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCPeering_To_v1alpha1_VPCPeering is an autogenerated conversion function.
func Convert_sdn_VPCPeering_To_v1alpha1_VPCPeering(in *sdn.VPCPeering, out *VPCPeering, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeering_To_v1alpha1_VPCPeering(in, out, s)
}

func autoConvert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(in *VPCPeeringList, out *sdn.VPCPeeringList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPCPeering)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(in *VPCPeeringList, out *sdn.VPCPeeringList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeeringList_To_sdn_VPCPeeringList(in, out, s)
}

func autoConvert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(in *sdn.VPCPeeringList, out *VPCPeeringList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPCPeering)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList is an autogenerated conversion function.
func Convert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(in *sdn.VPCPeeringList, out *VPCPeeringList, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeeringList_To_v1alpha1_VPCPeeringList(in, out, s)
}

func autoConvert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(in *VPCPeeringSpec, out *sdn.VPCPeeringSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LocalVPCRef_To_sdn_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCRef_To_sdn_VPCRef(&in.PeerRef, &out.PeerRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(in *VPCPeeringSpec, out *sdn.VPCPeeringSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeeringSpec_To_sdn_VPCPeeringSpec(in, out, s)
}

func autoConvert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(in *sdn.VPCPeeringSpec, out *VPCPeeringSpec, s conversion.Scope) error {
	if err := Convert_sdn_LocalVPCRef_To_v1alpha1_LocalVPCRef(&in.VPCRef, &out.VPCRef, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCRef_To_v1alpha1_VPCRef(&in.PeerRef, &out.PeerRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec is an autogenerated conversion function.
func Convert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(in *sdn.VPCPeeringSpec, out *VPCPeeringSpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeeringSpec_To_v1alpha1_VPCPeeringSpec(in, out, s)
}

func autoConvert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(in *VPCPeeringStatus, out *sdn.VPCPeeringStatus, s conversion.Scope) error {
	out.Phase = sdn.VPCPeeringPhase(in.Phase)
	out.PeerVNI = in.PeerVNI
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(in *VPCPeeringStatus, out *sdn.VPCPeeringStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCPeeringStatus_To_sdn_VPCPeeringStatus(in, out, s)
}

func autoConvert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(in *sdn.VPCPeeringStatus, out *VPCPeeringStatus, s conversion.Scope) error {
	out.Phase = VPCPeeringPhase(in.Phase)
	out.PeerVNI = in.PeerVNI
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus is an autogenerated conversion function.
func Convert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(in *sdn.VPCPeeringStatus, out *VPCPeeringStatus, s conversion.Scope) error {
	return autoConvert_sdn_VPCPeeringStatus_To_v1alpha1_VPCPeeringStatus(in, out, s)
}

func autoConvert_v1alpha1_VPCRef_To_sdn_VPCRef(in *VPCRef, out *sdn.VPCRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_VPCRef_To_sdn_VPCRef is an autogenerated conversion function.
func Convert_v1alpha1_VPCRef_To_sdn_VPCRef(in *VPCRef, out *sdn.VPCRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCRef_To_sdn_VPCRef(in, out, s)
}

func autoConvert_sdn_VPCRef_To_v1alpha1_VPCRef(in *sdn.VPCRef, out *VPCRef, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_sdn_VPCRef_To_v1alpha1_VPCRef is an autogenerated conversion function.
func Convert_sdn_VPCRef_To_v1alpha1_VPCRef(in *sdn.VPCRef, out *VPCRef, s conversion.Scope) error {
	return autoConvert_sdn_VPCRef_To_v1alpha1_VPCRef(in, out, s)
}

func autoConvert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in *VPCSpec, out *sdn.VPCSpec, s conversion.Scope) error {
	out.CIDRs = *(*[]string)(unsafe.Pointer(&in.CIDRs))
	out.MTU = in.MTU
	return nil
}

// Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in *VPCSpec, out *sdn.VPCSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in, out, s)
}

func autoConvert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in *sdn.VPCSpec, out *VPCSpec, s conversion.Scope) error {
	out.CIDRs = *(*[]string)(unsafe.Pointer(&in.CIDRs))
	out.MTU = in.MTU
	return nil
}

// Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec is an autogenerated conversion function.
func Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in *sdn.VPCSpec, out *VPCSpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in, out, s)
}

func autoConvert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in *VPCStatus, out *sdn.VPCStatus, s conversion.Scope) error {
	out.VNI = in.VNI
	out.Phase = sdn.VPCPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in *VPCStatus, out *sdn.VPCStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in, out, s)
}

func autoConvert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in *sdn.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	out.VNI = in.VNI
	out.Phase = VPCPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus is an autogenerated conversion function.
func Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in *sdn.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	return autoConvert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in, out, s)
}
