//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 The Cozyplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	sdn "github.com/lllamnyp/cozyplane/api/sdn"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*VPC)(nil), (*sdn.VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPC_To_sdn_VPC(a.(*VPC), b.(*sdn.VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPC)(nil), (*VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPC_To_v1alpha1_VPC(a.(*sdn.VPC), b.(*VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCList)(nil), (*sdn.VPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCList_To_sdn_VPCList(a.(*VPCList), b.(*sdn.VPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCList)(nil), (*VPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCList_To_v1alpha1_VPCList(a.(*sdn.VPCList), b.(*VPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCSpec)(nil), (*sdn.VPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(a.(*VPCSpec), b.(*sdn.VPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCSpec)(nil), (*VPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(a.(*sdn.VPCSpec), b.(*VPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCStatus)(nil), (*sdn.VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(a.(*VPCStatus), b.(*sdn.VPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sdn.VPCStatus)(nil), (*VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(a.(*sdn.VPCStatus), b.(*VPCStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_VPC_To_sdn_VPC(in *VPC, out *sdn.VPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VPC_To_sdn_VPC is an autogenerated conversion function.
func Convert_v1alpha1_VPC_To_sdn_VPC(in *VPC, out *sdn.VPC, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPC_To_sdn_VPC(in, out, s)
}

func autoConvert_sdn_VPC_To_v1alpha1_VPC(in *sdn.VPC, out *VPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sdn_VPC_To_v1alpha1_VPC is an autogenerated conversion function.
func Convert_sdn_VPC_To_v1alpha1_VPC(in *sdn.VPC, out *VPC, s conversion.Scope) error {
	return autoConvert_sdn_VPC_To_v1alpha1_VPC(in, out, s)
}

func autoConvert_v1alpha1_VPCList_To_sdn_VPCList(in *VPCList, out *sdn.VPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sdn.VPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VPCList_To_sdn_VPCList is an autogenerated conversion function.
func Convert_v1alpha1_VPCList_To_sdn_VPCList(in *VPCList, out *sdn.VPCList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCList_To_sdn_VPCList(in, out, s)
}

func autoConvert_sdn_VPCList_To_v1alpha1_VPCList(in *sdn.VPCList, out *VPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sdn_VPCList_To_v1alpha1_VPCList is an autogenerated conversion function.
func Convert_sdn_VPCList_To_v1alpha1_VPCList(in *sdn.VPCList, out *VPCList, s conversion.Scope) error {
	return autoConvert_sdn_VPCList_To_v1alpha1_VPCList(in, out, s)
}

func autoConvert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in *VPCSpec, out *sdn.VPCSpec, s conversion.Scope) error {
	out.CIDRs = *(*[]string)(unsafe.Pointer(&in.CIDRs))
	out.MTU = in.MTU
	return nil
}

// Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec is an autogenerated conversion function.
func Convert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in *VPCSpec, out *sdn.VPCSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCSpec_To_sdn_VPCSpec(in, out, s)
}

func autoConvert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in *sdn.VPCSpec, out *VPCSpec, s conversion.Scope) error {
	out.CIDRs = *(*[]string)(unsafe.Pointer(&in.CIDRs))
	out.MTU = in.MTU
	return nil
}

// Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec is an autogenerated conversion function.
func Convert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in *sdn.VPCSpec, out *VPCSpec, s conversion.Scope) error {
	return autoConvert_sdn_VPCSpec_To_v1alpha1_VPCSpec(in, out, s)
}

func autoConvert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in *VPCStatus, out *sdn.VPCStatus, s conversion.Scope) error {
	out.VNI = in.VNI
	out.Phase = sdn.VPCPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in *VPCStatus, out *sdn.VPCStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCStatus_To_sdn_VPCStatus(in, out, s)
}

func autoConvert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in *sdn.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	out.VNI = in.VNI
	out.Phase = VPCPhase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus is an autogenerated conversion function.
func Convert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in *sdn.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	return autoConvert_sdn_VPCStatus_To_v1alpha1_VPCStatus(in, out, s)
}
