// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package datapath

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type overlayAddr128 struct {
	_ structs.HostLayout
	B [16]uint8
}

type overlayBridgeEp struct {
	_     structs.HostLayout
	Net   uint32
	Pad   uint32
	VpcIp overlayAddr128
}

type overlayCozyMac struct {
	_    structs.HostLayout
	Addr [6]uint8
	Pad  [2]uint8
}

type overlayCtFwdKey struct {
	_          structs.HostLayout
	Proto      uint8
	Pad        [3]uint8
	Net        uint32
	ClientIp   overlayAddr128
	FabricIp   overlayAddr128
	ClientPort uint16
	PodPort    uint16
}

type overlayCtRevKey struct {
	_       structs.HostLayout
	Proto   uint8
	Pad     uint8
	GwPort  uint16
	Net     uint32
	VpcIp   overlayAddr128
	PodPort uint16
	Pad2    uint16
}

type overlayCtRevVal struct {
	_          structs.HostLayout
	FabricIp   overlayAddr128
	ClientIp   overlayAddr128
	ClientPort uint16
	Pad        uint16
}

type overlayDnsCtKey struct {
	_      structs.HostLayout
	Proto  uint8
	Pad    uint8
	Sport  uint16
	Fabric overlayAddr128
}

type overlayEndpoint struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	Pad     [2]uint8
}

type overlayFloatNet struct {
	_    structs.HostLayout
	Base uint32
	Mask uint32
}

type overlayGwEntry struct {
	_      structs.HostLayout
	GwIp   overlayAddr128
	NodeIp uint32
	Pad    uint32
}

type overlayLocalKey struct {
	_   structs.HostLayout
	Net uint32
	Ip  overlayAddr128
}

type overlayLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	ScopeNet  uint32
	Addr      overlayAddr128
}

type overlayPeerKey struct {
	_      structs.HostLayout
	SrcNet uint32
	DstNet uint32
}

type overlaySgCidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Net       uint32
	Port      uint16
	Proto     uint16
	Client    overlayAddr128
}

type overlaySgEgressCidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	SrcNet    uint32
	Port      uint16
	Proto     uint16
	Dest      overlayAddr128
}

type overlaySgEgressKey struct {
	_      structs.HostLayout
	SrcNet uint32
	DstNet uint32
	Group  uint16
	Port   uint16
	Proto  uint8
	Pad    [3]uint8
}

type overlaySgRuleKey struct {
	_      structs.HostLayout
	Net    uint32
	SrcNet uint32
	Group  uint16
	Port   uint16
	Proto  uint8
	Pad    [3]uint8
}

type overlaySvcFwdKey struct {
	_      structs.HostLayout
	Net    uint32
	Proto  uint8
	Pad    uint8
	Cport  uint16
	Client overlayAddr128
	Vip    overlayAddr128
	Vport  uint16
	Pad2   uint16
}

type overlaySvcFwdVal struct {
	_       structs.HostLayout
	Backend overlayAddr128
	Tport   uint16
	Hairpin uint16
}

type overlaySvcKey struct {
	_     structs.HostLayout
	Net   uint32
	Vip   overlayAddr128
	Proto uint8
	Pad   uint8
	Port  uint16
}

type overlaySvcRevKey struct {
	_       structs.HostLayout
	Net     uint32
	Proto   uint8
	Pad     uint8
	Cport   uint16
	Backend overlayAddr128
	Client  overlayAddr128
	Tport   uint16
	Pad2    uint16
}

type overlaySvcRevVal struct {
	_     structs.HostLayout
	Vip   overlayAddr128
	Vport uint16
	Pad   uint16
}

type overlaySvcVal struct {
	_     structs.HostLayout
	N     uint32
	Flags uint32
	Be    [16]struct {
		_    structs.HostLayout
		Ip   overlayAddr128
		Port uint16
		Pad  uint16
	}
}

type overlayVpcCounter struct {
	_         structs.HostLayout
	TxPackets uint64
	TxBytes   uint64
	RxPackets uint64
	RxBytes   uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	overlayMapBridges               = "bridges"
	overlayMapCtFwd                 = "ct_fwd"
	overlayMapCtRev                 = "ct_rev"
	overlayMapDnsCt                 = "dns_ct"
	overlayMapDnsIps                = "dns_ips"
	overlayMapFabricOf              = "fabric_of"
	overlayMapFloatNet              = "float_net"
	overlayMapFloatUplinkMac        = "float_uplink_mac"
	overlayMapFloating              = "floating"
	overlayMapFloatingEgress        = "floating_egress"
	overlayMapGateways              = "gateways"
	overlayMapInternal              = "internal"
	overlayMapLocals                = "locals"
	overlayMapMasqSrcs              = "masq_srcs"
	overlayMapMigrateFwd            = "migrate_fwd"
	overlayMapNetworks              = "networks"
	overlayMapNodeIp6               = "node_ip6"
	overlayMapNodeRemotes           = "node_remotes"
	overlayMapParams                = "params"
	overlayMapPeers                 = "peers"
	overlayMapPorts                 = "ports"
	overlayMapRemotes               = "remotes"
	overlayMapSgCidr                = "sg_cidr"
	overlayMapSgDrops               = "sg_drops"
	overlayMapSgEgress              = "sg_egress"
	overlayMapSgEgressCidr          = "sg_egress_cidr"
	overlayMapSgMembers             = "sg_members"
	overlayMapSgRules               = "sg_rules"
	overlayMapSvcFwd                = "svc_fwd"
	overlayMapSvcRev                = "svc_rev"
	overlayMapSvcVips               = "svc_vips"
	overlayMapUplinkMac             = "uplink_mac"
	overlayMapVpcCounters           = "vpc_counters"
	overlayProgCozyplaneFromOverlay = "cozyplane_from_overlay"
	overlayProgCozyplaneFromPod     = "cozyplane_from_pod"
	overlayProgCozyplaneFromUplink  = "cozyplane_from_uplink"
	overlayProgCozyplaneToPod       = "cozyplane_to_pod"
)

// loadOverlay returns the embedded CollectionSpec for overlay.
func loadOverlay() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OverlayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load overlay: %w", err)
	}

	return spec, err
}

// loadOverlayObjects loads overlay and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*overlayObjects
//	*overlayPrograms
//	*overlayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOverlayObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadOverlay()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// overlaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlaySpecs struct {
	overlayProgramSpecs
	overlayMapSpecs
	overlayVariableSpecs
}

// overlayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayProgramSpecs struct {
	CozyplaneFromOverlay *ebpf.ProgramSpec `ebpf:"cozyplane_from_overlay"`
	CozyplaneFromPod     *ebpf.ProgramSpec `ebpf:"cozyplane_from_pod"`
	CozyplaneFromUplink  *ebpf.ProgramSpec `ebpf:"cozyplane_from_uplink"`
	CozyplaneToPod       *ebpf.ProgramSpec `ebpf:"cozyplane_to_pod"`
}

// overlayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayMapSpecs struct {
	Bridges        *ebpf.MapSpec `ebpf:"bridges"`
	CtFwd          *ebpf.MapSpec `ebpf:"ct_fwd"`
	CtRev          *ebpf.MapSpec `ebpf:"ct_rev"`
	DnsCt          *ebpf.MapSpec `ebpf:"dns_ct"`
	DnsIps         *ebpf.MapSpec `ebpf:"dns_ips"`
	FabricOf       *ebpf.MapSpec `ebpf:"fabric_of"`
	FloatNet       *ebpf.MapSpec `ebpf:"float_net"`
	FloatUplinkMac *ebpf.MapSpec `ebpf:"float_uplink_mac"`
	Floating       *ebpf.MapSpec `ebpf:"floating"`
	FloatingEgress *ebpf.MapSpec `ebpf:"floating_egress"`
	Gateways       *ebpf.MapSpec `ebpf:"gateways"`
	Internal       *ebpf.MapSpec `ebpf:"internal"`
	Locals         *ebpf.MapSpec `ebpf:"locals"`
	MasqSrcs       *ebpf.MapSpec `ebpf:"masq_srcs"`
	MigrateFwd     *ebpf.MapSpec `ebpf:"migrate_fwd"`
	Networks       *ebpf.MapSpec `ebpf:"networks"`
	NodeIp6        *ebpf.MapSpec `ebpf:"node_ip6"`
	NodeRemotes    *ebpf.MapSpec `ebpf:"node_remotes"`
	Params         *ebpf.MapSpec `ebpf:"params"`
	Peers          *ebpf.MapSpec `ebpf:"peers"`
	Ports          *ebpf.MapSpec `ebpf:"ports"`
	Remotes        *ebpf.MapSpec `ebpf:"remotes"`
	SgCidr         *ebpf.MapSpec `ebpf:"sg_cidr"`
	SgDrops        *ebpf.MapSpec `ebpf:"sg_drops"`
	SgEgress       *ebpf.MapSpec `ebpf:"sg_egress"`
	SgEgressCidr   *ebpf.MapSpec `ebpf:"sg_egress_cidr"`
	SgMembers      *ebpf.MapSpec `ebpf:"sg_members"`
	SgRules        *ebpf.MapSpec `ebpf:"sg_rules"`
	SvcFwd         *ebpf.MapSpec `ebpf:"svc_fwd"`
	SvcRev         *ebpf.MapSpec `ebpf:"svc_rev"`
	SvcVips        *ebpf.MapSpec `ebpf:"svc_vips"`
	UplinkMac      *ebpf.MapSpec `ebpf:"uplink_mac"`
	VpcCounters    *ebpf.MapSpec `ebpf:"vpc_counters"`
}

// overlayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayVariableSpecs struct {
}

// overlayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayObjects struct {
	overlayPrograms
	overlayMaps
	overlayVariables
}

func (o *overlayObjects) Close() error {
	return _OverlayClose(
		&o.overlayPrograms,
		&o.overlayMaps,
	)
}

// overlayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayMaps struct {
	Bridges        *ebpf.Map `ebpf:"bridges"`
	CtFwd          *ebpf.Map `ebpf:"ct_fwd"`
	CtRev          *ebpf.Map `ebpf:"ct_rev"`
	DnsCt          *ebpf.Map `ebpf:"dns_ct"`
	DnsIps         *ebpf.Map `ebpf:"dns_ips"`
	FabricOf       *ebpf.Map `ebpf:"fabric_of"`
	FloatNet       *ebpf.Map `ebpf:"float_net"`
	FloatUplinkMac *ebpf.Map `ebpf:"float_uplink_mac"`
	Floating       *ebpf.Map `ebpf:"floating"`
	FloatingEgress *ebpf.Map `ebpf:"floating_egress"`
	Gateways       *ebpf.Map `ebpf:"gateways"`
	Internal       *ebpf.Map `ebpf:"internal"`
	Locals         *ebpf.Map `ebpf:"locals"`
	MasqSrcs       *ebpf.Map `ebpf:"masq_srcs"`
	MigrateFwd     *ebpf.Map `ebpf:"migrate_fwd"`
	Networks       *ebpf.Map `ebpf:"networks"`
	NodeIp6        *ebpf.Map `ebpf:"node_ip6"`
	NodeRemotes    *ebpf.Map `ebpf:"node_remotes"`
	Params         *ebpf.Map `ebpf:"params"`
	Peers          *ebpf.Map `ebpf:"peers"`
	Ports          *ebpf.Map `ebpf:"ports"`
	Remotes        *ebpf.Map `ebpf:"remotes"`
	SgCidr         *ebpf.Map `ebpf:"sg_cidr"`
	SgDrops        *ebpf.Map `ebpf:"sg_drops"`
	SgEgress       *ebpf.Map `ebpf:"sg_egress"`
	SgEgressCidr   *ebpf.Map `ebpf:"sg_egress_cidr"`
	SgMembers      *ebpf.Map `ebpf:"sg_members"`
	SgRules        *ebpf.Map `ebpf:"sg_rules"`
	SvcFwd         *ebpf.Map `ebpf:"svc_fwd"`
	SvcRev         *ebpf.Map `ebpf:"svc_rev"`
	SvcVips        *ebpf.Map `ebpf:"svc_vips"`
	UplinkMac      *ebpf.Map `ebpf:"uplink_mac"`
	VpcCounters    *ebpf.Map `ebpf:"vpc_counters"`
}

func (m *overlayMaps) Close() error {
	return _OverlayClose(
		m.Bridges,
		m.CtFwd,
		m.CtRev,
		m.DnsCt,
		m.DnsIps,
		m.FabricOf,
		m.FloatNet,
		m.FloatUplinkMac,
		m.Floating,
		m.FloatingEgress,
		m.Gateways,
		m.Internal,
		m.Locals,
		m.MasqSrcs,
		m.MigrateFwd,
		m.Networks,
		m.NodeIp6,
		m.NodeRemotes,
		m.Params,
		m.Peers,
		m.Ports,
		m.Remotes,
		m.SgCidr,
		m.SgDrops,
		m.SgEgress,
		m.SgEgressCidr,
		m.SgMembers,
		m.SgRules,
		m.SvcFwd,
		m.SvcRev,
		m.SvcVips,
		m.UplinkMac,
		m.VpcCounters,
	)
}

// overlayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayVariables struct {
}

// overlayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayPrograms struct {
	CozyplaneFromOverlay *ebpf.Program `ebpf:"cozyplane_from_overlay"`
	CozyplaneFromPod     *ebpf.Program `ebpf:"cozyplane_from_pod"`
	CozyplaneFromUplink  *ebpf.Program `ebpf:"cozyplane_from_uplink"`
	CozyplaneToPod       *ebpf.Program `ebpf:"cozyplane_to_pod"`
}

func (p *overlayPrograms) Close() error {
	return _OverlayClose(
		p.CozyplaneFromOverlay,
		p.CozyplaneFromPod,
		p.CozyplaneFromUplink,
		p.CozyplaneToPod,
	)
}

func _OverlayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed overlay_bpfel.o
var _OverlayBytes []byte
