// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package datapath

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type overlayBridgeEp struct {
	_     structs.HostLayout
	Net   uint32
	VpcIp uint32
}

type overlayCozyMac struct {
	_    structs.HostLayout
	Addr [6]uint8
	Pad  [2]uint8
}

type overlayCtFwdKey struct {
	_          structs.HostLayout
	Proto      uint8
	Pad        [3]uint8
	Net        uint32
	ClientIp   uint32
	FabricIp   uint32
	ClientPort uint16
	PodPort    uint16
}

type overlayCtRevKey struct {
	_       structs.HostLayout
	Proto   uint8
	Pad     uint8
	GwPort  uint16
	Net     uint32
	VpcIp   uint32
	PodPort uint16
	Pad2    uint16
}

type overlayCtRevVal struct {
	_          structs.HostLayout
	FabricIp   uint32
	ClientIp   uint32
	ClientPort uint16
	Pad        uint16
}

type overlayEndpoint struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	Pad     [2]uint8
}

type overlayGwEntry struct {
	_      structs.HostLayout
	GwIp   uint32
	NodeIp uint32
}

type overlayLocalKey struct {
	_   structs.HostLayout
	Net uint32
	Ip  uint32
}

type overlayLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	ScopeNet  uint32
	Addr      uint32
}

type overlayPeerKey struct {
	_      structs.HostLayout
	SrcNet uint32
	DstNet uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	overlayMapBridges               = "bridges"
	overlayMapCtFwd                 = "ct_fwd"
	overlayMapCtRev                 = "ct_rev"
	overlayMapFloating              = "floating"
	overlayMapFloatingEgress        = "floating_egress"
	overlayMapGateways              = "gateways"
	overlayMapInternal              = "internal"
	overlayMapLocals                = "locals"
	overlayMapNetworks              = "networks"
	overlayMapParams                = "params"
	overlayMapPeers                 = "peers"
	overlayMapPorts                 = "ports"
	overlayMapRemotes               = "remotes"
	overlayMapUplinkMac             = "uplink_mac"
	overlayProgCozyplaneFromOverlay = "cozyplane_from_overlay"
	overlayProgCozyplaneFromPod     = "cozyplane_from_pod"
	overlayProgCozyplaneFromUplink  = "cozyplane_from_uplink"
	overlayProgCozyplaneToPod       = "cozyplane_to_pod"
)

// loadOverlay returns the embedded CollectionSpec for overlay.
func loadOverlay() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OverlayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load overlay: %w", err)
	}

	return spec, err
}

// loadOverlayObjects loads overlay and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*overlayObjects
//	*overlayPrograms
//	*overlayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOverlayObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadOverlay()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// overlaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlaySpecs struct {
	overlayProgramSpecs
	overlayMapSpecs
	overlayVariableSpecs
}

// overlayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayProgramSpecs struct {
	CozyplaneFromOverlay *ebpf.ProgramSpec `ebpf:"cozyplane_from_overlay"`
	CozyplaneFromPod     *ebpf.ProgramSpec `ebpf:"cozyplane_from_pod"`
	CozyplaneFromUplink  *ebpf.ProgramSpec `ebpf:"cozyplane_from_uplink"`
	CozyplaneToPod       *ebpf.ProgramSpec `ebpf:"cozyplane_to_pod"`
}

// overlayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayMapSpecs struct {
	Bridges        *ebpf.MapSpec `ebpf:"bridges"`
	CtFwd          *ebpf.MapSpec `ebpf:"ct_fwd"`
	CtRev          *ebpf.MapSpec `ebpf:"ct_rev"`
	Floating       *ebpf.MapSpec `ebpf:"floating"`
	FloatingEgress *ebpf.MapSpec `ebpf:"floating_egress"`
	Gateways       *ebpf.MapSpec `ebpf:"gateways"`
	Internal       *ebpf.MapSpec `ebpf:"internal"`
	Locals         *ebpf.MapSpec `ebpf:"locals"`
	Networks       *ebpf.MapSpec `ebpf:"networks"`
	Params         *ebpf.MapSpec `ebpf:"params"`
	Peers          *ebpf.MapSpec `ebpf:"peers"`
	Ports          *ebpf.MapSpec `ebpf:"ports"`
	Remotes        *ebpf.MapSpec `ebpf:"remotes"`
	UplinkMac      *ebpf.MapSpec `ebpf:"uplink_mac"`
}

// overlayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayVariableSpecs struct {
}

// overlayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayObjects struct {
	overlayPrograms
	overlayMaps
	overlayVariables
}

func (o *overlayObjects) Close() error {
	return _OverlayClose(
		&o.overlayPrograms,
		&o.overlayMaps,
	)
}

// overlayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayMaps struct {
	Bridges        *ebpf.Map `ebpf:"bridges"`
	CtFwd          *ebpf.Map `ebpf:"ct_fwd"`
	CtRev          *ebpf.Map `ebpf:"ct_rev"`
	Floating       *ebpf.Map `ebpf:"floating"`
	FloatingEgress *ebpf.Map `ebpf:"floating_egress"`
	Gateways       *ebpf.Map `ebpf:"gateways"`
	Internal       *ebpf.Map `ebpf:"internal"`
	Locals         *ebpf.Map `ebpf:"locals"`
	Networks       *ebpf.Map `ebpf:"networks"`
	Params         *ebpf.Map `ebpf:"params"`
	Peers          *ebpf.Map `ebpf:"peers"`
	Ports          *ebpf.Map `ebpf:"ports"`
	Remotes        *ebpf.Map `ebpf:"remotes"`
	UplinkMac      *ebpf.Map `ebpf:"uplink_mac"`
}

func (m *overlayMaps) Close() error {
	return _OverlayClose(
		m.Bridges,
		m.CtFwd,
		m.CtRev,
		m.Floating,
		m.FloatingEgress,
		m.Gateways,
		m.Internal,
		m.Locals,
		m.Networks,
		m.Params,
		m.Peers,
		m.Ports,
		m.Remotes,
		m.UplinkMac,
	)
}

// overlayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayVariables struct {
}

// overlayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayPrograms struct {
	CozyplaneFromOverlay *ebpf.Program `ebpf:"cozyplane_from_overlay"`
	CozyplaneFromPod     *ebpf.Program `ebpf:"cozyplane_from_pod"`
	CozyplaneFromUplink  *ebpf.Program `ebpf:"cozyplane_from_uplink"`
	CozyplaneToPod       *ebpf.Program `ebpf:"cozyplane_to_pod"`
}

func (p *overlayPrograms) Close() error {
	return _OverlayClose(
		p.CozyplaneFromOverlay,
		p.CozyplaneFromPod,
		p.CozyplaneFromUplink,
		p.CozyplaneToPod,
	)
}

func _OverlayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed overlay_bpfel.o
var _OverlayBytes []byte
