// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package datapath

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type overlayEndpoint struct {
	_       structs.HostLayout
	Ifindex uint32
	Mac     [6]uint8
	Pad     [2]uint8
}

type overlayGwEntry struct {
	_      structs.HostLayout
	GwIp   uint32
	NodeIp uint32
}

type overlayLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type overlayPeerKey struct {
	_      structs.HostLayout
	SrcNet uint32
	DstNet uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	overlayMapGateways              = "gateways"
	overlayMapLocals                = "locals"
	overlayMapNetworks              = "networks"
	overlayMapParams                = "params"
	overlayMapPeers                 = "peers"
	overlayMapPorts                 = "ports"
	overlayMapRemotes               = "remotes"
	overlayProgCozyplaneFromOverlay = "cozyplane_from_overlay"
	overlayProgCozyplaneFromPod     = "cozyplane_from_pod"
	overlayProgCozyplaneToPod       = "cozyplane_to_pod"
)

// loadOverlay returns the embedded CollectionSpec for overlay.
func loadOverlay() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OverlayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load overlay: %w", err)
	}

	return spec, err
}

// loadOverlayObjects loads overlay and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*overlayObjects
//	*overlayPrograms
//	*overlayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOverlayObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadOverlay()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// overlaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlaySpecs struct {
	overlayProgramSpecs
	overlayMapSpecs
	overlayVariableSpecs
}

// overlayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayProgramSpecs struct {
	CozyplaneFromOverlay *ebpf.ProgramSpec `ebpf:"cozyplane_from_overlay"`
	CozyplaneFromPod     *ebpf.ProgramSpec `ebpf:"cozyplane_from_pod"`
	CozyplaneToPod       *ebpf.ProgramSpec `ebpf:"cozyplane_to_pod"`
}

// overlayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayMapSpecs struct {
	Gateways *ebpf.MapSpec `ebpf:"gateways"`
	Locals   *ebpf.MapSpec `ebpf:"locals"`
	Networks *ebpf.MapSpec `ebpf:"networks"`
	Params   *ebpf.MapSpec `ebpf:"params"`
	Peers    *ebpf.MapSpec `ebpf:"peers"`
	Ports    *ebpf.MapSpec `ebpf:"ports"`
	Remotes  *ebpf.MapSpec `ebpf:"remotes"`
}

// overlayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayVariableSpecs struct {
}

// overlayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayObjects struct {
	overlayPrograms
	overlayMaps
	overlayVariables
}

func (o *overlayObjects) Close() error {
	return _OverlayClose(
		&o.overlayPrograms,
		&o.overlayMaps,
	)
}

// overlayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayMaps struct {
	Gateways *ebpf.Map `ebpf:"gateways"`
	Locals   *ebpf.Map `ebpf:"locals"`
	Networks *ebpf.Map `ebpf:"networks"`
	Params   *ebpf.Map `ebpf:"params"`
	Peers    *ebpf.Map `ebpf:"peers"`
	Ports    *ebpf.Map `ebpf:"ports"`
	Remotes  *ebpf.Map `ebpf:"remotes"`
}

func (m *overlayMaps) Close() error {
	return _OverlayClose(
		m.Gateways,
		m.Locals,
		m.Networks,
		m.Params,
		m.Peers,
		m.Ports,
		m.Remotes,
	)
}

// overlayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayVariables struct {
}

// overlayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayPrograms struct {
	CozyplaneFromOverlay *ebpf.Program `ebpf:"cozyplane_from_overlay"`
	CozyplaneFromPod     *ebpf.Program `ebpf:"cozyplane_from_pod"`
	CozyplaneToPod       *ebpf.Program `ebpf:"cozyplane_to_pod"`
}

func (p *overlayPrograms) Close() error {
	return _OverlayClose(
		p.CozyplaneFromOverlay,
		p.CozyplaneFromPod,
		p.CozyplaneToPod,
	)
}

func _OverlayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed overlay_bpfel.o
var _OverlayBytes []byte
