// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package vpnclientfilter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type clientAddressKey struct {
	_       structs.HostLayout
	Family  uint32
	Address [16]uint8
}

type clientDestinationKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Family    uint32
	Peer      uint32
	Address   [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	clientMapDenied            = "denied"
	clientMapDestinations      = "destinations"
	clientMapSources           = "sources"
	clientProgVpnClientIngress = "vpn_client_ingress"
)

// loadClient returns the embedded CollectionSpec for client.
func loadClient() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ClientBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load client: %w", err)
	}

	return spec, err
}

// loadClientObjects loads client and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*clientObjects
//	*clientPrograms
//	*clientMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadClientObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadClient()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// clientSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clientSpecs struct {
	clientProgramSpecs
	clientMapSpecs
	clientVariableSpecs
}

// clientProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clientProgramSpecs struct {
	VpnClientIngress *ebpf.ProgramSpec `ebpf:"vpn_client_ingress"`
}

// clientMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clientMapSpecs struct {
	Denied       *ebpf.MapSpec `ebpf:"denied"`
	Destinations *ebpf.MapSpec `ebpf:"destinations"`
	Sources      *ebpf.MapSpec `ebpf:"sources"`
}

// clientVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clientVariableSpecs struct {
}

// clientObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadClientObjects or ebpf.CollectionSpec.LoadAndAssign.
type clientObjects struct {
	clientPrograms
	clientMaps
	clientVariables
}

func (o *clientObjects) Close() error {
	return _ClientClose(
		&o.clientPrograms,
		&o.clientMaps,
	)
}

// clientMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadClientObjects or ebpf.CollectionSpec.LoadAndAssign.
type clientMaps struct {
	Denied       *ebpf.Map `ebpf:"denied"`
	Destinations *ebpf.Map `ebpf:"destinations"`
	Sources      *ebpf.Map `ebpf:"sources"`
}

func (m *clientMaps) Close() error {
	return _ClientClose(
		m.Denied,
		m.Destinations,
		m.Sources,
	)
}

// clientVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadClientObjects or ebpf.CollectionSpec.LoadAndAssign.
type clientVariables struct {
}

// clientPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadClientObjects or ebpf.CollectionSpec.LoadAndAssign.
type clientPrograms struct {
	VpnClientIngress *ebpf.Program `ebpf:"vpn_client_ingress"`
}

func (p *clientPrograms) Close() error {
	return _ClientClose(
		p.VpnClientIngress,
	)
}

func _ClientClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed client_bpfel.o
var _ClientBytes []byte
